apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attestor
resources:
  - namespace.yaml
  - api-serviceaccount.yaml
  - worker-serviceaccount.yaml
  - configmap.yaml
  - release-runtime-pki-pvc.yaml
  - api-service.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - api-hpa.yaml
  - worker-hpa.yaml
  - api-pdb.yaml
  - worker-pdb.yaml
  - gateway.yaml
  - httproute.yaml
