/**
 * Attestor service API route constant types.
 *
 * This module is re-exported by ../api-types.ts for compatibility.
 */

export const API_ROUTES = {
  METRICS: '/api/v1/metrics',
  PIPELINE_RUN: '/api/v1/pipeline/run',
  PIPELINE_RUN_ASYNC: '/api/v1/pipeline/run-async',
  PIPELINE_STATUS: '/api/v1/pipeline/status/:jobId',
  VERIFY: '/api/v1/verify',
  FILING_EXPORT: '/api/v1/filing/export',
  ACCOUNT_USAGE: '/api/v1/account/usage',
  ACCOUNT_SUMMARY: '/api/v1/account',
  ACCOUNT_FEATURES: '/api/v1/account/features',
  ACCOUNT_EMAIL_DELIVERIES: '/api/v1/account/email/deliveries',
  ACCOUNT_OIDC: '/api/v1/account/oidc',
  ACCOUNT_SAML: '/api/v1/account/saml',
  ACCOUNT_PASSKEYS: '/api/v1/account/passkeys',
  ACCOUNT_PASSKEYS_REGISTER_OPTIONS: '/api/v1/account/passkeys/register/options',
  ACCOUNT_PASSKEYS_REGISTER_VERIFY: '/api/v1/account/passkeys/register/verify',
  ACCOUNT_PASSKEYS_DELETE: '/api/v1/account/passkeys/:id/delete',
  RETIRED_ACCOUNT_PLAN_CHECKOUT: '/api/v1/account/billing/checkout',
  ACCOUNT_BILLING_WORKFLOWS: '/api/v1/account/billing/workflows',
  ACCOUNT_BILLING_WORKFLOW_CHECKOUT: '/api/v1/account/billing/workflows/checkout',
  ACCOUNT_BILLING_PORTAL: '/api/v1/account/billing/portal',
  ACCOUNT_BILLING_EXPORT: '/api/v1/account/billing/export',
  ACCOUNT_BILLING_RECONCILIATION: '/api/v1/account/billing/reconciliation',
  ADMIN_ACCOUNTS: '/api/v1/admin/accounts',
  ADMIN_EMAIL_DELIVERIES: '/api/v1/admin/email/deliveries',
  ADMIN_ACCOUNT_FEATURES: '/api/v1/admin/accounts/:id/features',
  ADMIN_ACCOUNT_BILLING_EXPORT: '/api/v1/admin/accounts/:id/billing/export',
  ADMIN_ACCOUNT_BILLING_RECONCILIATION: '/api/v1/admin/accounts/:id/billing/reconciliation',
  ADMIN_ACCOUNT_SUSPEND: '/api/v1/admin/accounts/:id/suspend',
  ADMIN_ACCOUNT_REACTIVATE: '/api/v1/admin/accounts/:id/reactivate',
  ADMIN_ACCOUNT_ARCHIVE: '/api/v1/admin/accounts/:id/archive',
  ADMIN_ACCOUNT_ATTACH_STRIPE: '/api/v1/admin/accounts/:id/billing/stripe',
  ADMIN_PLANS: '/api/v1/admin/plans',
  ADMIN_AUDIT: '/api/v1/admin/audit',
  ADMIN_BILLING_EVENTS: '/api/v1/admin/billing/events',
  ADMIN_METRICS: '/api/v1/admin/metrics',
  ADMIN_QUEUE: '/api/v1/admin/queue',
  ADMIN_QUEUE_DLQ: '/api/v1/admin/queue/dlq',
  ADMIN_QUEUE_RETRY: '/api/v1/admin/queue/jobs/:id/retry',
  ADMIN_TENANT_KEYS: '/api/v1/admin/tenant-keys',
  ADMIN_TENANT_KEY_ROTATE: '/api/v1/admin/tenant-keys/:id/rotate',
  ADMIN_TENANT_KEY_DEACTIVATE: '/api/v1/admin/tenant-keys/:id/deactivate',
  ADMIN_TENANT_KEY_REACTIVATE: '/api/v1/admin/tenant-keys/:id/reactivate',
  ADMIN_TENANT_KEY_RECOVER: '/api/v1/admin/tenant-keys/:id/recover',
  ADMIN_TENANT_KEY_REVOKE: '/api/v1/admin/tenant-keys/:id/revoke',
  ADMIN_USAGE: '/api/v1/admin/usage',
  AUTH_PASSKEY_OPTIONS: '/api/v1/auth/passkeys/options',
  AUTH_PASSKEY_VERIFY: '/api/v1/auth/passkeys/verify',
  AUTH_OIDC_LOGIN: '/api/v1/auth/oidc/login',
  AUTH_OIDC_CALLBACK: '/api/v1/auth/oidc/callback',
  AUTH_SAML_METADATA: '/api/v1/auth/saml/metadata',
  AUTH_SAML_LOGIN: '/api/v1/auth/saml/login',
  AUTH_SAML_ACS: '/api/v1/auth/saml/acs',
  BILLING_STRIPE_WEBHOOK: '/api/v1/billing/stripe/webhook',
  EMAIL_MAILGUN_WEBHOOK: '/api/v1/email/mailgun/webhook',
  EMAIL_SENDGRID_WEBHOOK: '/api/v1/email/sendgrid/webhook',
  STARTUP: '/api/v1/startup',
  HEALTH: '/api/v1/health',
  DOMAINS: '/api/v1/domains',
  CONNECTORS: '/api/v1/connectors',
} as const;
