apiVersion: apps/v1
kind: Deployment
metadata:
  name: attestor-otel-gateway
  namespace: attestor-observability
spec:
  template:
    spec:
      containers:
        - name: otel-collector
          image: grafana/alloy:v1.16.1@sha256:51aeb9d829239345070619dad3edd6873186f913c84f45b365b74574fcb38ec0
          command:
            - bin/otelcol
          env:
            - name: GRAFANA_CLOUD_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: attestor-otel-gateway-grafana-cloud
                  key: grafana-cloud-otlp-endpoint
            - name: GRAFANA_CLOUD_OTLP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: attestor-otel-gateway-grafana-cloud
                  key: grafana-cloud-otlp-username
            - name: GRAFANA_CLOUD_OTLP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: attestor-otel-gateway-grafana-cloud
                  key: grafana-cloud-otlp-token
            - name: TEMPO_OTLP_ENDPOINT
              $patch: delete
            - name: LOKI_OTLP_ENDPOINT
              $patch: delete
