import * as staticDeps from './api-route-runtime-static-deps.js';

const {
  deleteCookie, getCookie, runFinancialPipeline, buildCounterpartyEnvelope,
  verifyOidcToken, classifyIdentitySource, buildVerificationKit, verifyCertificate,
  derivePublicKeyIdentity, verifyTrustChain, accountPasskeyCredentialView, accountUserActionTokenView,
  accountUserDetailedMfaView, accountUserDetailedOidcView, accountUserDetailedPasskeyView, accountUserDetailedSamlView,
  accountUserView, asAuthenticationResponse, asRegistrationResponse, deriveSignupTenantId,
  normalizePasskeyAuthenticatorHint, parsePasskeyAuthenticationChallenge, parsePasskeyRegistrationChallenge, sessionCookieName,
  ATTESTOR_SERVICE_VERSION, buildTotpOtpAuthUrl, accountMfaEncryptionKeySource, decryptTotpSecret,
  encryptTotpSecret, generateRecoveryCodes, generateTotpSecretBase32, isPendingTotpEnrollmentFresh,
  totpSummary, verifyAndConsumeRecoveryCode, verifyTotpCodeWithStep, buildHostedOidcAuthorizationRequest,
  completeHostedOidcAuthorization, hostedOidcAllowsAutomaticLinking, hostedOidcStateKeySource, linkAccountUserOidcIdentity,
  buildAccountUserPasskeyCredentialRecord, buildHostedPasskeyAuthenticationOptions, buildHostedPasskeyRegistrationOptions, generateHostedPasskeyUserHandle,
  passkeyCredentialToWebAuthnCredential, verifyHostedPasskeyAuthentication, verifyHostedPasskeyRegistration, buildHostedSamlAuthorizationRequest,
  completeHostedSamlAuthorization, getHostedSamlMetadata, hostedSamlAllowsAutomaticLinking, hostedSamlRelayStateKeySource,
  linkAccountUserSamlIdentity, verifyAccountUserPasswordRecord, canEnqueueTenantAsyncJob, getAsyncQueueSummary,
  getAsyncRetryPolicy, getJobStatus, listFailedPipelineJobs, retryFailedPipelineJob,
  submitPipelineJob, getTenantAsyncExecutionCoordinatorStatus, getTenantAsyncWeightedDispatchCoordinatorStatus, claimStripeBillingEvent,
  finalizeStripeBillingEvent, isBillingEventLedgerConfigured, listBillingEvents, releaseStripeBillingEventClaim,
  upsertStripeCharges, buildHostedFeatureServiceView, buildHostedBillingExport, renderHostedBillingExportCsv,
  buildHostedBillingReconciliation, appendAdminAuditRecordState, attachStripeBillingToAccountState, canConsumePipelineRunState,
  claimProcessedStripeWebhookState, consumeAccountUserActionTokenState, consumeAccountUserRecoveryCodeState, consumePipelineRunState,
  countAccountUsersForAccountState, createAccountUserState, finalizeProcessedStripeWebhookState, findAccountUserActionTokenByTokenState,
  findAccountUserByEmailState, findAccountUserByIdState, findAccountUserByOidcIdentityState, findAccountUserByPasskeyCredentialIdState,
  findAccountUserBySamlIdentityState, findHostedAccountByIdState, findHostedAccountByTenantIdState, findHostedBillingEntitlementByAccountIdState,
  findWorkflowEntitlementByTenantAndWorkflowState, findTenantRecordByTenantIdState, getUsageContextState, isSharedControlPlaneConfigured,
  issueAccountInviteTokenState, issueAccountMfaLoginTokenState, issueAccountPasskeyChallengeTokenState, issueAccountSessionState,
  issuePasswordResetTokenState, issueTenantApiKeyState, listAccountUserActionTokensByAccountIdState, listAccountUsersByAccountIdState,
  listAdminAuditRecordsState, listAsyncDeadLetterRecordsState, listHostedAccountsState, listHostedBillingEntitlementsState,
  listWorkflowEntitlementsState, listHostedEmailDeliveriesState, listTenantKeyRecordsState, ensurePipelineIdempotencyStateReady,
  lookupAdminIdempotencyState, lookupPipelineIdempotencyState, lookupProcessedStripeWebhookState, provisionHostedAccountState,
  queryUsageLedgerState, recordAccountUserLoginState, recordAccountUserTotpVerificationStepState, recordAdminIdempotencyState,
  recordPipelineIdempotencyState, recordHostedEmailProviderEventState, recordHostedSamlReplayState, recordProcessedStripeWebhookState,
  recoverTenantApiKeyState, releaseProcessedStripeWebhookClaimState, revokeAccountSessionByTokenState, revokeAccountSessionsForAccountState,
  revokeAccountSessionsForUserState, revokeAccountUserActionTokenState, revokeAccountUserActionTokensForUserState, revokeTenantApiKeyState,
  rotateTenantApiKeyState, saveAccountUserActionTokenRecordState, saveAccountUserRecordState, setAccountUserPasswordState,
  setAccountUserStatusState, setHostedAccountStatusState, setTenantApiKeyStatusState, upsertAsyncDeadLetterRecordState,
  upsertHostedBillingEntitlementState, upsertPendingWorkflowEntitlementState, upsertWorkflowEntitlementFromStripeState, deliverHostedInviteEmail,
  deliverHostedPasswordResetEmail, getHostedEmailDeliveryStatus, buildFinanceActionReleaseMaterial, buildFinanceActionReleaseObservation,
  buildFinanceCommunicationReleaseMaterial, buildFinanceCommunicationReleaseObservation, buildFinanceFilingReleaseMaterial, buildFinanceFilingReleaseObservation,
  createFinanceActionReleaseCandidateFromReport, createFinanceCommunicationReleaseCandidateFromReport, createFinanceFilingReleaseCandidateFromReport, createFinanceReviewerQueueItem,
  finalizeFinanceFilingReleaseDecision, FINANCE_FILING_ADAPTER_ID, ReleaseVerificationError, resolveReleaseTokenFromRequest,
  verifyReleaseAuthorization, evaluateApiHighAvailabilityState, accountApiKeyView, adminAccountView,
  adminAuditView, adminPlanView, adminTenantKeyView, billingEntitlementView,
  billingEventView, accountMfaErrorResponse, createHostedAccountSupport, stripeBillingErrorResponse,
  hashJsonValue, getMailgunWebhookStatus, mailgunSignatureTokenDigest, mailgunEventTypeToStatusHint,
  parseMailgunWebhookEvent, verifySignedMailgunWebhook, getTelemetryStatus, observeBillingWebhookEvent,
  renderPrometheusMetrics, DEFAULT_HOSTED_PLAN_ID, SELF_HOST_PLAN_ID, defaultRateLimitWindowSeconds,
  resolvePlanSpec, applyRateLimitHeaders, schemaAttestationSummaryFromConnector, schemaAttestationSummaryFromFull,
  getTenantPipelineRateLimit, reserveTenantPipelineRequest, createRequestSigners, currentAccountAccess,
  currentAccountRole, currentAdminAuthorized, currentMetricsAuthorized, currentReleaseEvaluationContext,
  currentReleaseRequester, currentTenant, requireAccountSession, setSessionCookieForRecord,
  renderReleaseReviewerQueueDetailPage, renderReleaseReviewerQueueInboxPage, asyncBackendMode, bullmqQueue,
  currentAsyncSubmissionReservations, inProcessJobs, inProcessTenantQueueSnapshot, redisMode,
  releaseAsyncSubmission, reserveAsyncSubmission, rlsActivationResult, getSecretEnvelopeStatus,
  getSendGridWebhookStatus, parseSendGridWebhookEvents, sendGridEventTypeToStatusHint, verifySignedSendGridWebhook,
  renderFinancialReportingLandingPage, renderFinancialReportingProofPage, renderHostedReturnPage, committedEvidenceContentType,
  committedFinancialPacket, readCommittedEvidence, createHostedBillingPortalSession, createHostedWorkflowCheckoutSession,
  extractActiveEntitlementsFromSummary, listHostedStripeActiveEntitlements, isSupportedStripeWebhookEvent, metadataStringValue,
  parseStripeChargeStatus, stripeClient, stripeReferenceId, unixSecondsToIso,
  tenantKeyStorePolicy,
} = staticDeps;
import type { AppRegistries } from './registries.js';
import { createReleaseRuntimeBootstrap } from './release-runtime.js';
import {
  evaluateSharedAuthorityRuntimeReadiness as evaluateSharedAuthorityRuntimeReadinessState,
} from './shared-authority-readiness.js';
import {
  evaluateProductionStoragePath as evaluateProductionStoragePathState,
} from './production-storage-path.js';
import {
  evaluateConsequenceSharedStoreProfile as evaluateConsequenceSharedStoreProfileState,
} from './consequence-shared-store-profile.js';
import {
  evaluateGenericAdmissionProtectedRoute,
} from '../generic-admission-protected-route.js';
import {
  createRuntimeHostedGenericAdmissionDpopProofReplayStore,
} from '../hosted/hosted-generic-admission-dpop-proof-replay-store.js';
import {
  resolveHostedGenericAdmissionDpopSenderConfirmation,
} from '../hosted/hosted-generic-admission-sender-confirmation.js';
import {
  releaseRuntimeDurabilitySummary,
  resolveRuntimeProfile,
} from './runtime-profile.js';
import {
  buildAccountRouteDeps,
  buildAdminRouteDeps,
  buildPipelineRouteDeps,
  buildReleasePolicyControlRouteDeps,
  buildReleaseReviewRouteDeps,
  buildWebhookRouteDeps,
} from './http-route-builders.js';
import {
  createHttpRouteRuntime,
  createRuntimeInfra,
  type AppRouteDeps,
  type AppRuntime,
} from './runtime.js';

export interface CreateApiHttpRouteRuntimeInput {
  registries: AppRegistries;
  serviceInstanceId: string;
  startTime: number;
}

type ApiRouteDeps = AppRouteDeps<typeof committedFinancialPacket>;

export async function createApiHttpRouteRuntime(
  input: CreateApiHttpRouteRuntimeInput,
): Promise<AppRuntime<typeof committedFinancialPacket>> {
  const { registries, serviceInstanceId, startTime } = input;
  const { domainRegistry, connectorRegistry, filingRegistry } = registries;
  const runtimeProfile = resolveRuntimeProfile();
  const {
    releaseRuntimeStoreModes,
    releaseRuntimeRequestPathDiagnostics,
    releaseRuntimeDurability,
    runtimeProfileDiagnostics,
    pki,
    pkiReady,
    releaseSigningProvider,
    financeReleaseDecisionLog,
    apiReleaseReviewerQueueStore,
    apiReleaseIntrospectionStore,
    apiReleaseIntrospector,
    apiReleaseTokenIssuer,
    apiReleaseEvidencePackStore,
    apiReleaseEvidencePackIssuer,
    apiReleaseVerificationKeyPromise,
    apiReleaseVerificationKeysPromise,
    apiReleaseDegradedModeGrantStore,
    policyControlPlaneStore,
    policyActivationApprovalStore,
    policyMutationAuditLog,
    financeReleaseDecisionEngine,
    financeCommunicationReleaseShadowEvaluator,
    financeActionReleaseShadowEvaluator,
  } = await createReleaseRuntimeBootstrap({
    runtimeProfile,
    allowPreflightOnDurabilityViolation: runtimeProfile.id === 'production-shared',
  });
  const productionStoragePath = evaluateProductionStoragePathState({
    runtimeProfileId: runtimeProfile.id,
  });
  const consequenceSharedStoreProfile = evaluateConsequenceSharedStoreProfileState({
    runtimeProfileId: runtimeProfile.id,
    productionStoragePath,
  });
  const genericAdmissionIssuerBoundary =
    releaseSigningProvider.signingBoundary === 'external-kms-hsm'
      ? 'external-kms-hsm'
      : 'runtime-release-token-issuer';
  const genericAdmissionDpopProofReplayStore =
    await createRuntimeHostedGenericAdmissionDpopProofReplayStore({
      runtimeProfileId: runtimeProfile.id,
      sharedAuthorityRequestPathReady:
        releaseRuntimeRequestPathDiagnostics.usesSharedAuthorityStores,
    });
  const genericAdmissionProtectedRoute = evaluateGenericAdmissionProtectedRoute({
    runtimeProfileId: runtimeProfile.id,
    requireProtectedReleaseTokenForHighRisk: true,
    issuerConfigured: true,
    issuerBoundary: genericAdmissionIssuerBoundary,
    issuerBoundaryEvidence: {
      source: 'runtime-signing-provider-diagnostics',
      issuerBoundary: genericAdmissionIssuerBoundary,
      productionReady: releaseSigningProvider.productionReady,
      liveProviderVerified: false,
      liveProviderProofState: 'not-provided',
      rawProviderResponseStored: false,
    },
    tokenIntrospectionStoreConfigured: true,
    tokenIntrospectionStoreDurability:
      releaseRuntimeStoreModes['release-token-introspection'] === 'shared'
        ? 'shared'
        : 'local',
    replayConsumptionStoreConfigured: true,
    replayConsumptionStoreDurability:
      releaseRuntimeStoreModes['release-token-introspection'] === 'shared'
        ? 'shared'
        : 'local',
    senderConfirmationSource: 'dpop-jkt',
    senderProofReplayStoreConfigured: true,
    senderProofReplayStoreDurability: genericAdmissionDpopProofReplayStore.durability,
    failClosedOnMissingIssuer: true,
    shadowRecordsRawToken: false,
    admissionOrShadowStoresRawToken: false,
    rawTokenReturnedOnlyToCaller: true,
  });
  const {
    currentHostedAccount,
    readHostedBillingEntitlement,
    syncHostedBillingEntitlement,
    syncHostedBillingEntitlementForTenant,
    findHostedAccountByStripeRefs,
  } = createHostedAccountSupport({
    DEFAULT_HOSTED_PLAN_ID,
    findHostedAccountByTenantId: findHostedAccountByTenantIdState,
    findHostedAccountById: findHostedAccountByIdState,
    listHostedAccounts: listHostedAccountsState,
    findTenantRecordByTenantId: findTenantRecordByTenantIdState,
    getUsageContext: getUsageContextState,
    getTenantPipelineRateLimit,
    findHostedBillingEntitlementByAccountId: findHostedBillingEntitlementByAccountIdState,
    upsertHostedBillingEntitlement: upsertHostedBillingEntitlementState,
    revokeAccountSessionsForAccount: revokeAccountSessionsForAccountState,
  });

  const publicSiteRouteDeps = {
    committedFinancialPacket,
    renderFinancialReportingLandingPage,
    renderFinancialReportingProofPage,
    renderHostedReturnPage,
    readCommittedEvidence,
    committedEvidenceContentType,
  } satisfies ApiRouteDeps['publicSite'];

  const safeAccountAuthKeySource = (
    resolve: () => 'dedicated' | 'local-admin-fallback',
  ): 'dedicated' | 'local-admin-fallback' | 'not-configured' => {
    try {
      return resolve();
    } catch {
      return 'not-configured';
    }
  };

  const coreRouteDeps = {
    evaluateApiHighAvailabilityState,
    redisMode,
    asyncBackendMode,
    isSharedControlPlaneConfigured,
    serviceInstanceId,
    serviceVersion: ATTESTOR_SERVICE_VERSION,
    startTime,
    domainRegistry,
    connectorRegistry,
    filingRegistry,
    pkiReady,
    releaseSigningProvider,
    pki,
    apiReleaseVerificationKeysPromise,
    runtimeProfileDiagnostics,
    releaseRuntimeRequestPathDiagnostics,
    evaluateSharedAuthorityRuntimeReadiness: ({ runtimeProfileId }) =>
      evaluateSharedAuthorityRuntimeReadinessState({
        runtimeProfileId: runtimeProfileId === runtimeProfile.id ? runtimeProfile.id : null,
        requestPathUsesSharedStores:
          releaseRuntimeRequestPathDiagnostics.usesSharedAuthorityStores,
      }),
    evaluateProductionStoragePath: ({ runtimeProfileId }) =>
      evaluateProductionStoragePathState({
        runtimeProfileId: runtimeProfileId === runtimeProfile.id ? runtimeProfile.id : null,
      }),
    evaluateConsequenceSharedStoreProfile: ({ runtimeProfileId }) =>
      evaluateConsequenceSharedStoreProfileState({
        runtimeProfileId: runtimeProfileId === runtimeProfile.id ? runtimeProfile.id : null,
      }),
    genericAdmissionProtectedRoute,
    rlsActivationResult,
    accountAuthKeySources: {
      mfa: safeAccountAuthKeySource(accountMfaEncryptionKeySource),
      oidc: safeAccountAuthKeySource(hostedOidcStateKeySource),
      saml: safeAccountAuthKeySource(hostedSamlRelayStateKeySource),
    },
  } satisfies ApiRouteDeps['core'];

  const accountRouteDeps = buildAccountRouteDeps({
    hashJsonValue,
    appendAdminAuditRecordState,
    ensurePipelineIdempotencyStateReady,
    lookupPipelineIdempotencyState,
    recordPipelineIdempotencyState,
    countAccountUsersForAccountState,
    createAccountUserState,
    findAccountUserByEmailState,
    deriveSignupTenantId,
    resolvePlanSpec,
    SELF_HOST_PLAN_ID,
    DEFAULT_HOSTED_PLAN_ID,
    provisionHostedAccountState,
    issueAccountSessionState,
    recordAccountUserLoginState,
    syncHostedBillingEntitlementForTenant,
    verifyAccountUserPasswordRecord,
    findHostedAccountByIdState,
    totpSummary,
    issueAccountMfaLoginTokenState,
    findTenantRecordByTenantIdState,
    listTenantKeyRecordsState,
    tenantKeyStorePolicy,
    issueTenantApiKeyState,
    rotateTenantApiKeyState,
    setTenantApiKeyStatusState,
    revokeTenantApiKeyState,
    now: () => new Date().toISOString(),
    listAccountUsersByAccountIdState,
    listAccountUserActionTokensByAccountIdState,
    findAccountUserActionTokenByTokenState,
    issueAccountInviteTokenState,
    revokeAccountUserActionTokenState,
    consumeAccountUserActionTokenState,
    findAccountUserByIdState,
    setAccountUserStatusState,
    revokeAccountSessionsForUserState,
    revokeAccountUserActionTokensForUserState,
    issuePasswordResetTokenState,
    setAccountUserPasswordState,
    saveAccountUserActionTokenRecordState,
    deliverHostedInviteEmail,
    deliverHostedPasswordResetEmail,
    findAccountUserByEmail: findAccountUserByEmailState,
    issueAccountSession: issueAccountSessionState,
    recordAccountUserLogin: recordAccountUserLoginState,
    findHostedAccountById: findHostedAccountByIdState,
    issueAccountMfaLoginToken: issueAccountMfaLoginTokenState,
    issueAccountPasskeyChallengeToken: issueAccountPasskeyChallengeTokenState,
    findAccountUserActionTokenByToken: findAccountUserActionTokenByTokenState,
    findAccountUserById: findAccountUserByIdState,
    findAccountUserByPasskeyCredentialId: findAccountUserByPasskeyCredentialIdState,
    saveAccountUserRecord: saveAccountUserRecordState,
    recordAccountUserTotpVerificationStep: recordAccountUserTotpVerificationStepState,
    consumeAccountUserRecoveryCode: consumeAccountUserRecoveryCodeState,
    consumeAccountUserActionToken: consumeAccountUserActionTokenState,
    revokeAccountUserActionTokensForUser: revokeAccountUserActionTokensForUserState,
    recordHostedSamlReplay: recordHostedSamlReplayState,
    findAccountUserBySamlIdentity: findAccountUserBySamlIdentityState,
    findAccountUserByOidcIdentity: findAccountUserByOidcIdentityState,
    getUsageContext: getUsageContextState,
    setAccountUserPassword: setAccountUserPasswordState,
    revokeAccountSessionsForUser: revokeAccountSessionsForUserState,
    saveAccountUserActionTokenRecord: saveAccountUserActionTokenRecordState,
    revokeAccountSessionByToken: revokeAccountSessionByTokenState,
    listHostedEmailDeliveries: listHostedEmailDeliveriesState,
    currentHostedAccount,
    setSessionCookieForRecord,
    accountUserView,
    adminAccountView,
    accountApiKeyView,
    buildHostedPasskeyAuthenticationOptions,
    asAuthenticationResponse,
    parsePasskeyAuthenticationChallenge,
    verifyHostedPasskeyAuthentication,
    passkeyCredentialToWebAuthnCredential,
    getHostedSamlMetadata,
    buildHostedSamlAuthorizationRequest,
    completeHostedSamlAuthorization,
    hostedSamlAllowsAutomaticLinking,
    linkAccountUserSamlIdentity,
    buildHostedOidcAuthorizationRequest,
    completeHostedOidcAuthorization,
    hostedOidcAllowsAutomaticLinking,
    linkAccountUserOidcIdentity,
    verifyTotpCodeWithStep,
    verifyAndConsumeRecoveryCode,
    isPendingTotpEnrollmentFresh,
    requireAccountSession,
    currentAccountAccess,
    buildHostedPasskeyRegistrationOptions,
    parsePasskeyRegistrationChallenge,
    asRegistrationResponse,
    verifyHostedPasskeyRegistration,
    buildAccountUserPasskeyCredentialRecord,
    generateHostedPasskeyUserHandle,
    accountUserDetailedMfaView,
    accountUserDetailedOidcView,
    accountUserDetailedSamlView,
    accountUserDetailedPasskeyView,
    accountPasskeyCredentialView,
    decryptTotpSecret,
    getSecretEnvelopeStatus,
    encryptTotpSecret,
    generateRecoveryCodes,
    generateTotpSecretBase32,
    buildTotpOtpAuthUrl,
    normalizePasskeyAuthenticatorHint,
    currentAccountRole,
    getTenantPipelineRateLimit,
    readHostedBillingEntitlement,
    buildHostedFeatureServiceView,
    accountUserActionTokenView,
    getCookie,
    deleteCookie,
    sessionCookieName,
    accountMfaErrorResponse,
    createHostedWorkflowCheckoutSession,
    listWorkflowEntitlements: listWorkflowEntitlementsState,
    findWorkflowEntitlementByTenantAndWorkflow: findWorkflowEntitlementByTenantAndWorkflowState,
    upsertPendingWorkflowEntitlement: upsertPendingWorkflowEntitlementState,
    stripeBillingErrorResponse,
    createHostedBillingPortalSession,
    buildHostedBillingExport,
    renderHostedBillingExportCsv,
    buildHostedBillingReconciliation,
    billingEntitlementView,
    currentTenant,
  });

  const {
    adminRouteDeps,
    adminMutationRequest,
    finalizeAdminMutation,
  } = buildAdminRouteDeps({
    hashJsonValue,
    lookupAdminIdempotencyState,
    recordAdminIdempotencyState,
    appendAdminAuditRecordState,
    resolvePlanSpec,
    DEFAULT_HOSTED_PLAN_ID,
    provisionHostedAccountState,
    attachStripeBillingToAccountState,
    setHostedAccountStatusState,
    revokeAccountSessionsForAccountState,
    readHostedBillingEntitlement,
    tenantKeyStorePolicy,
    issueTenantApiKeyState,
    rotateTenantApiKeyState,
    setTenantApiKeyStatusState,
    recoverTenantApiKeyState,
    revokeTenantApiKeyState,
    syncHostedBillingEntitlement,
    syncHostedBillingEntitlementForTenant,
    now: () => new Date().toISOString(),
    listTenantKeyRecordsState,
    listHostedAccountsState,
    findHostedAccountByIdState,
    listAdminAuditRecordsState,
    listHostedBillingEntitlementsState,
    listHostedEmailDeliveriesState,
    listAsyncDeadLetterRecordsState,
    queryUsageLedgerState,
    findTenantRecordByTenantIdState,
    findHostedAccountByTenantIdState,
    currentAdminAuthorized,
    adminTenantKeyView,
    adminAccountView,
    buildHostedBillingExport,
    buildHostedBillingReconciliation,
    renderHostedBillingExportCsv,
    billingEntitlementView,
    getUsageContext: getUsageContextState,
    buildHostedFeatureServiceView,
    getTenantAsyncExecutionCoordinatorStatus,
    getTenantAsyncWeightedDispatchCoordinatorStatus,
    adminPlanView,
    defaultRateLimitWindowSeconds,
    adminAuditView,
    isBillingEventLedgerConfigured,
    listBillingEvents,
    billingEventView,
    renderPrometheusMetrics: (version) => renderPrometheusMetrics(version, {
      runtimeProfile: runtimeProfileDiagnostics.profile.id,
      releaseRuntimeReady: runtimeProfileDiagnostics.durability.ready,
      requestPathContract: releaseRuntimeRequestPathDiagnostics.contract,
      requestPathUsesSharedStores:
        releaseRuntimeRequestPathDiagnostics.usesSharedAuthorityStores,
    }),
    currentMetricsAuthorized,
    getTelemetryStatus,
    getHostedEmailDeliveryStatus,
    getSecretEnvelopeStatus,
    asyncBackendMode,
    bullmqQueue,
    getAsyncQueueSummary,
    getAsyncRetryPolicy,
    inProcessJobs,
    inProcessTenantQueueSnapshot,
    listFailedPipelineJobs,
    retryFailedPipelineJob,
    apiReleaseIntrospectionStore,
    releaseDegradedModeGrantStore: apiReleaseDegradedModeGrantStore,
  });

  const releaseReviewRouteDeps = buildReleaseReviewRouteDeps({
    renderReleaseReviewerQueueInboxPage,
    renderReleaseReviewerQueueDetailPage,
    currentAdminAuthorized,
    apiReleaseReviewerQueueStore,
    financeReleaseDecisionLog,
    apiReleaseTokenIssuer,
    apiReleaseEvidencePackStore,
    apiReleaseEvidencePackIssuer,
    apiReleaseIntrospectionStore,
    resolveReleaseReviewTokenConfirmation: async ({ context, issuedAt }) => {
      const confirmation = await resolveHostedGenericAdmissionDpopSenderConfirmation({
        proofJwt: context.req.header('DPoP') ?? null,
        httpMethod: context.req.method,
        httpUri: context.req.url,
        now: issuedAt,
        proofReplayStore: genericAdmissionDpopProofReplayStore,
      });
      return confirmation.confirmation;
    },
    adminMutationRequest,
    finalizeAdminMutation,
  });

  const releasePolicyControlRouteDeps = buildReleasePolicyControlRouteDeps({
    currentAdminAuthorized,
    policyControlPlaneStore,
    policyActivationApprovalStore,
    policyMutationAuditLog,
    requireAtomicPolicyLifecycle: runtimeProfile.id === 'production-shared',
    adminMutationRequest,
    finalizeAdminMutation,
  });

  const pipelineRouteDeps = buildPipelineRouteDeps({
    checkQuota: canConsumePipelineRunState,
    consumeRun: consumePipelineRunState,
    hashJsonValue,
    ensurePipelineIdempotencyStateReady,
    lookupPipelineIdempotencyState,
    recordPipelineIdempotencyState,
    recordOverageMetering: async () => ({
      provider: 'stripe',
      status: 'not_applicable',
      reason: 'account_plan_overage_metering_retired_use_workflow_entitlement_metering',
      eventName: null,
      eventIdentifier: null,
      value: 0,
      mock: process.env.ATTESTOR_STRIPE_USE_MOCK === 'true',
    }),
    upsertDeadLetterRecord: upsertAsyncDeadLetterRecordState,
    currentTenant,
    reserveTenantPipelineRequest,
    applyRateLimitHeaders,
    connectorRegistry,
    verifyOidcToken,
    classifyIdentitySource,
    createRequestSigners,
    runFinancialPipeline,
    buildVerificationKit,
    createFinanceCommunicationReleaseCandidateFromReport,
    buildFinanceCommunicationReleaseMaterial,
    buildFinanceCommunicationReleaseObservation,
    financeCommunicationReleaseShadowEvaluator,
    createFinanceActionReleaseCandidateFromReport,
    buildFinanceActionReleaseMaterial,
    buildFinanceActionReleaseObservation,
    financeActionReleaseShadowEvaluator,
    createFinanceFilingReleaseCandidateFromReport,
    FINANCE_FILING_ADAPTER_ID,
    buildFinanceFilingReleaseMaterial,
    financeReleaseDecisionEngine,
    financeReleaseDecisionLog,
    buildFinanceFilingReleaseObservation,
    currentReleaseRequester,
    currentReleaseEvaluationContext,
    finalizeFinanceFilingReleaseDecision,
    resolveFinanceFilingReleaseTokenConfirmation: async ({ context, report }) => {
      const confirmation = await resolveHostedGenericAdmissionDpopSenderConfirmation({
        proofJwt: context.req.header('DPoP') ?? null,
        httpMethod: context.req.method,
        httpUri: context.req.url,
        now: report.timestamp,
        proofReplayStore: genericAdmissionDpopProofReplayStore,
      });
      return confirmation.confirmation;
    },
    createFinanceReviewerQueueItem,
    apiReleaseReviewerQueueStore,
    apiReleaseTokenIssuer,
    apiReleaseEvidencePackStore,
    apiReleaseEvidencePackIssuer,
    apiReleaseIntrospectionStore,
    schemaAttestationSummaryFromFull,
    schemaAttestationSummaryFromConnector,
    filingRegistry,
    buildCounterpartyEnvelope,
    verifyCertificate,
    verifyTrustChain,
    derivePublicKeyIdentity,
    apiReleaseVerificationKeyPromise,
    resolveReleaseTokenFromRequest,
    verifyReleaseAuthorization,
    apiReleaseIntrospector,
    ReleaseVerificationError,
    asyncBackendMode,
    bullmqQueue,
    canEnqueueTenantAsyncJob,
    currentAsyncSubmissionReservations,
    reserveAsyncSubmission,
    releaseAsyncSubmission,
    getAsyncRetryPolicy,
    getAsyncQueueSummary,
    submitPipelineJob,
    getTenantPipelineRateLimit,
    inProcessTenantQueueSnapshot,
    inProcessJobs,
    pki,
    getJobStatus,
  });

  const webhookRouteDeps = buildWebhookRouteDeps({
    stripeClient,
    observeBillingWebhookEvent,
    isBillingEventLedgerConfigured,
    isSharedControlPlaneConfigured,
    claimStripeBillingEvent,
    claimProcessedStripeWebhookState,
    lookupProcessedStripeWebhookState,
    finalizeProcessedStripeWebhookState,
    recordProcessedStripeWebhookState,
    releaseProcessedStripeWebhookClaimState,
    finalizeStripeBillingEvent,
    releaseStripeBillingEventClaim,
    isSupportedStripeWebhookEvent,
    stripeReferenceId,
    metadataStringValue,
    upsertWorkflowEntitlementFromStripeState,
    findHostedAccountByStripeRefs,
    syncHostedBillingEntitlement,
    appendAdminAuditRecordState,
    billingEntitlementView,
    listHostedStripeActiveEntitlements,
    extractActiveEntitlementsFromSummary,
    parseStripeChargeStatus,
    upsertStripeCharges,
    unixSecondsToIso,
    getSendGridWebhookStatus,
    verifySignedSendGridWebhook,
    parseSendGridWebhookEvents,
    getMailgunWebhookStatus,
    parseMailgunWebhookEvent,
    verifySignedMailgunWebhook,
    mailgunSignatureTokenDigest,
    async findEmailDeliveryById(deliveryId) {
      const existing = await listHostedEmailDeliveriesState({
        deliveryId,
        limit: 1,
      });
      return existing.records[0] ?? null;
    },
    recordEmailProviderEvent: recordHostedEmailProviderEventState,
    sendGridEventTypeToStatusHint,
    mailgunEventTypeToStatusHint,
    now: () => new Date().toISOString(),
  });

  return createHttpRouteRuntime({
    registries,
    infra: createRuntimeInfra({
      instanceId: serviceInstanceId,
      startedAtEpochMs: startTime,
      asyncExecution: {
        backendMode: asyncBackendMode,
        redisMode,
      },
      security: {
        runtimeProfile: runtimeProfile.id,
        releaseRuntimeStoreModes,
        releaseRuntimeDurability: {
          ready: releaseRuntimeDurability.ready,
          summary: releaseRuntimeDurabilitySummary(releaseRuntimeDurability),
        },
        releaseRuntimeRequestPathDiagnostics,
        runtimeProfileDiagnostics,
        productionStoragePath,
        consequenceSharedStoreProfile,
        genericAdmissionProtectedRoute,
        rlsActivationResult,
        pkiReady,
        releaseSigningProvider,
      },
    }),
    httpRoutes: {
      publicSite: publicSiteRouteDeps,
      core: coreRouteDeps,
      account: accountRouteDeps,
      admin: adminRouteDeps,
      releaseReview: releaseReviewRouteDeps,
      releasePolicyControl: releasePolicyControlRouteDeps,
      pipeline: pipelineRouteDeps,
      webhook: webhookRouteDeps,
    },
    extraServices: {
      genericAdmissionProtectedIssuer: apiReleaseTokenIssuer,
      genericAdmissionProtectedIntrospectionStore: apiReleaseIntrospectionStore,
      genericAdmissionDpopProofReplayStore,
    },
  });
}
