import {
  X402_AGENTIC_PAYMENT_ADAPTER_SPEC_VERSION,
  X402_CHECKS,
  X402_EXACT_AUTHORIZATION_MODES,
  X402_FACILITATOR_PATHS,
  X402_HTTP_PAYMENT_REQUIRED_STATUS,
  X402_NETWORK_NAMESPACES,
  X402_OUTCOMES,
  X402_PAYMENT_REQUIRED_HEADER,
  X402_PAYMENT_RESPONSE_HEADER,
  X402_PAYMENT_SCHEMES,
  X402_PAYMENT_SIGNATURE_HEADER,
  X402_PROTOCOL_VERSION,
  X402_TRANSPORTS,
  type X402AgenticPaymentAdapterDescriptor,
} from './x402-agentic-payment-adapter-types.js';

export function x402AgenticPaymentAdapterDescriptor(): X402AgenticPaymentAdapterDescriptor {
  return Object.freeze({
    version: X402_AGENTIC_PAYMENT_ADAPTER_SPEC_VERSION,
    adapterKind: 'x402-payment',
    protocolVersion: X402_PROTOCOL_VERSION,
    paymentRequiredStatus: X402_HTTP_PAYMENT_REQUIRED_STATUS,
    headers: Object.freeze({
      paymentRequired: X402_PAYMENT_REQUIRED_HEADER,
      paymentSignature: X402_PAYMENT_SIGNATURE_HEADER,
      paymentResponse: X402_PAYMENT_RESPONSE_HEADER,
    }),
    transports: X402_TRANSPORTS,
    schemes: X402_PAYMENT_SCHEMES,
    networkNamespaces: X402_NETWORK_NAMESPACES,
    authorizationModes: X402_EXACT_AUTHORIZATION_MODES,
    facilitatorPaths: X402_FACILITATOR_PATHS,
    outcomes: X402_OUTCOMES,
    checks: X402_CHECKS,
    references: Object.freeze([
      'x402-v2',
      'HTTP-402',
      'PAYMENT-REQUIRED',
      'PAYMENT-SIGNATURE',
      'PAYMENT-RESPONSE',
      'CAIP-2',
      'EIP-3009',
      'EIP-712',
      'Permit2',
      'SPL-TransferChecked',
      'facilitator-verify',
      'facilitator-settle',
      'agent-budget',
      'agent-cadence',
      'metadata-privacy-filtering',
      'release-layer',
      'release-policy-control-plane',
      'release-enforcement-plane',
      'attestor-crypto-authorization-simulation',
    ]),
  });
}
