global:
  resolve_timeout: 5m

route:
  receiver: default
  group_by: [alertname, severity]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - alertname="Watchdog"
      receiver: watchdog
      repeat_interval: 1m
    - matchers:
        - team="security"
      receiver: security
      continue: true
    - matchers:
        - team="billing"
      receiver: billing
      continue: true
    - matchers:
        - severity="critical"
      receiver: critical
    - matchers:
        - severity="warning"
      receiver: warning

receivers:
  - name: default
    webhook_configs:
      - send_resolved: true
        url_file: /etc/alertmanager/secrets/default-webhook-url
  - name: watchdog
    webhook_configs:
      - send_resolved: true
        url_file: /etc/alertmanager/secrets/watchdog-webhook-url
  - name: critical
    webhook_configs:
      - send_resolved: true
        url_file: /etc/alertmanager/secrets/critical-webhook-url
  - name: warning
    webhook_configs:
      - send_resolved: true
        url_file: /etc/alertmanager/secrets/warning-webhook-url
  - name: security
    webhook_configs:
      - send_resolved: true
        url_file: /etc/alertmanager/secrets/security-webhook-url
  - name: billing
    webhook_configs:
      - send_resolved: true
        url_file: /etc/alertmanager/secrets/billing-webhook-url

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: [alertname]
