import type { CryptoExecutionAdapterKind } from '../crypto-authorization-core/types.js';
import type { CryptoAdapterReadinessMatrixEntry } from './adapter-readiness-manifest-types.js';

const PRIVATE_DATA_BOUNDARY = Object.freeze({
  rawPayloadStored: false,
  rawProviderResponseStored: false,
  customerIdentifiersStored: false,
  privatePolicyThresholdsStored: false,
  solverRouteSecretsStored: false,
} as const);

export const CRYPTO_ADAPTER_READINESS_MATRIX = Object.freeze({
  'adapter-neutral': Object.freeze({
    matrixEntryId: 'adapter-neutral',
    adapterKind: null,
    surface: 'attestor-core',
    standards: Object.freeze(['attestor-core']),
    requiredPreflightSources: Object.freeze([] as const),
    recommendedPreflightSources: Object.freeze(['wallet-capabilities'] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'policy-scope-binding',
      'enforcement-presentation',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'wallet-call-api': Object.freeze({
    matrixEntryId: 'wallet-call-api',
    adapterKind: 'wallet-call-api',
    surface: 'wallet-rpc',
    standards: Object.freeze(['EIP-5792', 'ERC-7715', 'ERC-7902']),
    requiredPreflightSources: Object.freeze([
      'wallet-capabilities',
      'wallet-call-preparation',
    ] as const),
    recommendedPreflightSources: Object.freeze([] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'wallet-capabilities',
      'prepared-call-bundle',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'safe-guard': Object.freeze({
    matrixEntryId: 'safe-guard',
    adapterKind: 'safe-guard',
    surface: 'smart-account-guard',
    standards: Object.freeze(['Safe Guard', 'ERC-1271']),
    requiredPreflightSources: Object.freeze(['safe-guard'] as const),
    recommendedPreflightSources: Object.freeze(['wallet-call-preparation'] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'safe-transaction-hash',
      'guard-precheck',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'safe-module-guard': Object.freeze({
    matrixEntryId: 'safe-module-guard',
    adapterKind: 'safe-module-guard',
    surface: 'smart-account-guard',
    standards: Object.freeze(['Safe Module Guard', 'Safe Modules', 'ERC-1271']),
    requiredPreflightSources: Object.freeze(['safe-guard', 'module-hook'] as const),
    recommendedPreflightSources: Object.freeze(['wallet-call-preparation'] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'safe-module-transaction-hash',
      'module-hook-precheck',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'erc-4337-user-operation': Object.freeze({
    matrixEntryId: 'erc-4337-user-operation',
    adapterKind: 'erc-4337-user-operation',
    surface: 'account-abstraction-bundler',
    standards: Object.freeze(['ERC-4337', 'ERC-7562', 'ERC-1271']),
    requiredPreflightSources: Object.freeze([
      'erc-4337-validation',
      'erc-7562-validation-scope',
    ] as const),
    recommendedPreflightSources: Object.freeze(['wallet-capabilities'] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'user-operation-hash',
      'simulate-validation-result',
      'erc-7562-validation-scope',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'erc-7579-module': Object.freeze({
    matrixEntryId: 'erc-7579-module',
    adapterKind: 'erc-7579-module',
    surface: 'modular-account-runtime',
    standards: Object.freeze(['ERC-7579', 'ERC-4337']),
    requiredPreflightSources: Object.freeze(['module-hook'] as const),
    recommendedPreflightSources: Object.freeze([
      'erc-4337-validation',
      'erc-7562-validation-scope',
    ] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'module-installation-evidence',
      'module-hook-precheck',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'erc-6900-plugin': Object.freeze({
    matrixEntryId: 'erc-6900-plugin',
    adapterKind: 'erc-6900-plugin',
    surface: 'modular-account-runtime',
    standards: Object.freeze(['ERC-6900', 'ERC-4337']),
    requiredPreflightSources: Object.freeze(['module-hook'] as const),
    recommendedPreflightSources: Object.freeze([
      'erc-4337-validation',
      'erc-7562-validation-scope',
    ] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'plugin-manifest-approval',
      'module-hook-precheck',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'eip-7702-delegation': Object.freeze({
    matrixEntryId: 'eip-7702-delegation',
    adapterKind: 'eip-7702-delegation',
    surface: 'delegated-eoa-runtime',
    standards: Object.freeze(['EIP-7702', 'EIP-5792', 'ERC-7902']),
    requiredPreflightSources: Object.freeze(['eip-7702-authorization'] as const),
    recommendedPreflightSources: Object.freeze(['wallet-call-preparation'] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'authorization-list-tuple',
      'delegate-code-approval',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'x402-payment': Object.freeze({
    matrixEntryId: 'x402-payment',
    adapterKind: 'x402-payment',
    surface: 'agent-payment-http',
    standards: Object.freeze(['x402-v2', 'HTTP 402', 'EIP-3009']),
    requiredPreflightSources: Object.freeze(['x402-payment'] as const),
    recommendedPreflightSources: Object.freeze(['wallet-capabilities'] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'x402-payment-requirement',
      'x402-payment-signature',
      'x402-payment-response',
      'x402-payment-verification',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'custody-cosigner': Object.freeze({
    matrixEntryId: 'custody-cosigner',
    adapterKind: 'custody-cosigner',
    surface: 'custody-policy-engine',
    standards: Object.freeze(['custody-policy-engine', 'co-signer-callback']),
    requiredPreflightSources: Object.freeze(['custody-policy'] as const),
    recommendedPreflightSources: Object.freeze([] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'custody-policy-decision',
      'co-signer-response',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
  'intent-settlement': Object.freeze({
    matrixEntryId: 'intent-settlement',
    adapterKind: 'intent-settlement',
    surface: 'intent-solver',
    standards: Object.freeze(['intent-settlement', 'ERC-7683', 'solver-preflight']),
    requiredPreflightSources: Object.freeze(['intent-settlement'] as const),
    recommendedPreflightSources: Object.freeze(['wallet-capabilities'] as const),
    requiredHandoffArtifacts: Object.freeze([
      'attestor-release-authorization',
      'solver-route-commitment',
      'settlement-preflight',
    ] as const),
    terminalEvidenceClasses: Object.freeze(['admission-receipt'] as const),
    privateDataBoundary: PRIVATE_DATA_BOUNDARY,
  }),
} satisfies Record<
  CryptoExecutionAdapterKind | 'adapter-neutral',
  CryptoAdapterReadinessMatrixEntry
>);
