import { CRYPTO_ADMISSION_RECEIPT_CLASSIFICATIONS } from './telemetry-receipts.js';
import { CRYPTO_ADMISSION_NEGATIVE_CONFORMANCE_FIXTURES } from './conformance-fixtures-negative.js';
import {
  CRYPTO_ADMISSION_CONFORMANCE_FIXTURES_SPEC_VERSION,
  CRYPTO_ADMISSION_CONFORMANCE_FIXTURE_PATH,
  CRYPTO_ADMISSION_CONFORMANCE_REQUIRED_SURFACES,
  CRYPTO_ADMISSION_CONFORMANCE_RUNTIME_CHECKS,
  CRYPTO_ADMISSION_CONFORMANCE_SCHEMA_DIALECT,
  CRYPTO_ADMISSION_CONFORMANCE_SCHEMA_PATH,
  CRYPTO_ADMISSION_CONFORMANCE_TELEMETRY_SIGNALS,
  CRYPTO_ADMISSION_NEGATIVE_CONFORMANCE_CLASSES,
  type CryptoAdmissionConformanceDescriptor,
} from './conformance-fixtures-types.js';

export function cryptoAdmissionConformanceDescriptor():
CryptoAdmissionConformanceDescriptor {
  return Object.freeze({
    fixtureVersion: CRYPTO_ADMISSION_CONFORMANCE_FIXTURES_SPEC_VERSION,
    schemaDialect: CRYPTO_ADMISSION_CONFORMANCE_SCHEMA_DIALECT,
    fixturePath: CRYPTO_ADMISSION_CONFORMANCE_FIXTURE_PATH,
    schemaPath: CRYPTO_ADMISSION_CONFORMANCE_SCHEMA_PATH,
    requiredSurfaces: CRYPTO_ADMISSION_CONFORMANCE_REQUIRED_SURFACES,
    runtimeChecks: CRYPTO_ADMISSION_CONFORMANCE_RUNTIME_CHECKS,
    telemetrySignals: CRYPTO_ADMISSION_CONFORMANCE_TELEMETRY_SIGNALS,
    receiptClassifications: CRYPTO_ADMISSION_RECEIPT_CLASSIFICATIONS,
    negativeFixtureClasses: CRYPTO_ADMISSION_NEGATIVE_CONFORMANCE_CLASSES,
    negativeFixtureCount: CRYPTO_ADMISSION_NEGATIVE_CONFORMANCE_FIXTURES.length,
  });
}
