import type { ConsequenceAdmissionCorrectionCatalogEntry } from './contracts.js';

export const CONSEQUENCE_ADMISSION_CORRECTION_CATALOG_ENTRIES:
readonly ConsequenceAdmissionCorrectionCatalogEntry[] = Object.freeze([
  {
    reasonCode: 'policy-ref-missing',
    audience: 'model',
    disclosureLevel: 'actionable',
    missingFields: ['policyRef'],
    requiredEvidenceKinds: ['policy_ref'],
    retryableByModel: true,
    operatorOnly: false,
    safeSummary: 'Attach a bounded policy reference accepted by the customer environment.',
  },
  {
    reasonCode: 'evidence-ref-missing',
    audience: 'model',
    disclosureLevel: 'actionable',
    missingFields: ['evidenceRefs'],
    requiredEvidenceKinds: ['evidence_ref'],
    retryableByModel: true,
    operatorOnly: false,
    safeSummary: 'Attach evidence references instead of raw customer or private data.',
  },
  {
    reasonCode: 'amount-scope-missing',
    audience: 'model',
    disclosureLevel: 'actionable',
    missingFields: ['amount'],
    requiredEvidenceKinds: [],
    retryableByModel: true,
    operatorOnly: false,
    safeSummary: 'Provide the proposed amount scope as structured metadata.',
  },
  {
    reasonCode: 'recipient-scope-missing',
    audience: 'model',
    disclosureLevel: 'actionable',
    missingFields: ['recipient'],
    requiredEvidenceKinds: [],
    retryableByModel: true,
    operatorOnly: false,
    safeSummary: 'Provide a bounded recipient reference for the proposed consequence.',
  },
  {
    reasonCode: 'data-scope-missing',
    audience: 'model',
    disclosureLevel: 'actionable',
    missingFields: ['dataScope'],
    requiredEvidenceKinds: ['data_scope_ref'],
    retryableByModel: true,
    operatorOnly: false,
    safeSummary: 'Provide data scope metadata such as classification, fields, or record bounds.',
  },
  {
    reasonCode: 'authority-mode-missing',
    audience: 'model',
    disclosureLevel: 'actionable',
    missingFields: ['authorityMode'],
    requiredEvidenceKinds: ['authority_ref'],
    retryableByModel: true,
    operatorOnly: false,
    safeSummary: 'Provide the customer-approved authority mode or authority reference.',
  },
  {
    reasonCode: 'guard-input-provenance-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance'],
    requiredEvidenceKinds: ['guard_input_provenance_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Required guard input provenance must come from a trusted customer, operator, or Attestor runtime boundary.',
  },
  {
    reasonCode: 'guard-input-source-untrusted',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance.sourceClass'],
    requiredEvidenceKinds: ['trusted_guard_input_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Caller-supplied, model-generated, or unverified tool output cannot satisfy guard input provenance.',
  },
  {
    reasonCode: 'guard-input-digest-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance.sourceDigest'],
    requiredEvidenceKinds: ['guard_input_digest'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Guard input provenance must bind to digest material instead of raw guard inputs.',
  },
  {
    reasonCode: 'guard-input-timestamp-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance.recordedAt'],
    requiredEvidenceKinds: ['guard_input_freshness_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Guard input provenance must include a freshness timestamp.',
  },
  {
    reasonCode: 'guard-input-tenant-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance.tenantId'],
    requiredEvidenceKinds: ['guard_input_tenant_binding_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Guard input provenance must bind to the tenant boundary.',
  },
  {
    reasonCode: 'guard-input-authority-untrusted',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance.sourceClass'],
    requiredEvidenceKinds: ['trusted_guard_authority_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Untrusted guard input cannot satisfy authority checks.',
  },
  {
    reasonCode: 'guard-input-policy-untrusted',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance.sourceClass'],
    requiredEvidenceKinds: ['trusted_guard_policy_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Untrusted guard input cannot satisfy policy checks.',
  },
  {
    reasonCode: 'guard-input-evidence-untrusted',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance.sourceClass'],
    requiredEvidenceKinds: ['trusted_guard_evidence_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Untrusted guard input cannot satisfy evidence checks without customer or operator review.',
  },
  {
    reasonCode: 'guard-input-review',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance'],
    requiredEvidenceKinds: ['guard_input_review_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Guard input provenance is incomplete and must be reviewed before execution.',
  },
  {
    reasonCode: 'guard-input-block',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['guardInputProvenance'],
    requiredEvidenceKinds: ['trusted_guard_input_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Guard input provenance failed closed.',
  },
  {
    reasonCode: 'authority-source-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['authoritySources'],
    requiredEvidenceKinds: ['trusted_authority_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'A trusted authority source must be supplied by the customer gateway, operator workflow, or trusted authority record.',
  },
  {
    reasonCode: 'untrusted-content-authority-source',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['authoritySources'],
    requiredEvidenceKinds: ['trusted_authority_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Untrusted content cannot authorize the proposed consequence.',
  },
  {
    reasonCode: 'model-generated-authority-source',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['authoritySources'],
    requiredEvidenceKinds: ['trusted_authority_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Model-generated text cannot be used as authority for the proposed consequence.',
  },
  {
    reasonCode: 'trust-class-override-rejected',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['authoritySources.trustClass'],
    requiredEvidenceKinds: ['trusted_authority_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'A source cannot self-promote from untrusted content into trusted authority.',
  },
  {
    reasonCode: 'trusted-authority-evidence-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['authoritySources.evidenceDigest'],
    requiredEvidenceKinds: ['trusted_authority_evidence_digest'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Trusted authority sources must include evidence digest material.',
  },
  {
    reasonCode: 'trusted-evidence-not-authority',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['authoritySources'],
    requiredEvidenceKinds: ['trusted_authority_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Trusted evidence can support a decision, but it does not grant authority by itself.',
  },
  {
    reasonCode: 'mixed-trusted-and-untrusted-authority-source',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: ['authoritySources'],
    requiredEvidenceKinds: ['trusted_authority_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Mixed trusted and untrusted authority claims require customer or operator review.',
  },
  {
    reasonCode: 'authority-review-required',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: ['authoritySources'],
    requiredEvidenceKinds: ['trusted_authority_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Authority provenance is incomplete and must be reviewed before execution.',
  },
  {
    reasonCode: 'authority-block',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['authoritySources'],
    requiredEvidenceKinds: ['trusted_authority_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Authority provenance failed closed.',
  },
  {
    reasonCode: 'approval-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals'],
    requiredEvidenceKinds: ['approval_provenance_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance is required when approval is used as authority.',
  },
  {
    reasonCode: 'approval-source-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.sourceRef'],
    requiredEvidenceKinds: ['approval_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance must name the source system or workflow reference.',
  },
  {
    reasonCode: 'approval-source-untrusted',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals'],
    requiredEvidenceKinds: ['trusted_approval_provenance_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Untrusted content cannot be treated as approval.',
  },
  {
    reasonCode: 'approval-model-generated',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals'],
    requiredEvidenceKinds: ['trusted_approval_provenance_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Model-generated text cannot be used as approval.',
  },
  {
    reasonCode: 'approval-tool-output-unverified',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals'],
    requiredEvidenceKinds: ['verified_tool_approval_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Tool output must be verified before it can support approval provenance.',
  },
  {
    reasonCode: 'approval-state-not-approved',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.state'],
    requiredEvidenceKinds: ['approved_state_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance has not reached an approved state.',
  },
  {
    reasonCode: 'approval-state-rejected-or-revoked',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.state'],
    requiredEvidenceKinds: ['active_approval_state_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Rejected or revoked approvals fail closed.',
  },
  {
    reasonCode: 'reviewer-identity-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.reviewerRef'],
    requiredEvidenceKinds: ['reviewer_identity_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance must bind to a reviewer identity.',
  },
  {
    reasonCode: 'reviewer-authority-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.reviewerAuthorityDigest'],
    requiredEvidenceKinds: ['reviewer_authority_digest'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance must bind the reviewer authority evidence.',
  },
  {
    reasonCode: 'approval-digest-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.approvalDigest'],
    requiredEvidenceKinds: ['approval_digest'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance must carry a digest of the approval record.',
  },
  {
    reasonCode: 'approval-scope-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.scopeDigest'],
    requiredEvidenceKinds: ['approval_scope_digest'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance must bind the approved scope.',
  },
  {
    reasonCode: 'approval-issued-at-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.issuedAt'],
    requiredEvidenceKinds: ['approval_issued_at'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance must include an issued-at timestamp.',
  },
  {
    reasonCode: 'approval-issued-at-invalid',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.issuedAt'],
    requiredEvidenceKinds: ['approval_issued_at'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval issued-at timestamp must be valid.',
  },
  {
    reasonCode: 'approval-expired',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.expiresAt'],
    requiredEvidenceKinds: ['fresh_approval_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Expired approvals fail closed or require review.',
  },
  {
    reasonCode: 'approval-step-up-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.stepUpVerified'],
    requiredEvidenceKinds: ['step_up_approval_proof'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Step-up approval evidence is missing.',
  },
  {
    reasonCode: 'approval-signature-unverified',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.signatureVerificationInput'],
    requiredEvidenceKinds: ['signed_approval_verification'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Signed approval provenance must verify against the configured trust binding.',
  },
  {
    reasonCode: 'approval-trust-class-source-mismatch',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.trustClass'],
    requiredEvidenceKinds: ['trusted_approval_provenance_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval source kind determines trust class; caller overrides cannot promote it.',
  },
  {
    reasonCode: 'approval-duplicate-reviewer',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals.reviewerRef'],
    requiredEvidenceKinds: ['distinct_reviewer_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Multiple approvals must come from distinct reviewer identities when required.',
  },
  {
    reasonCode: 'approval-count-insufficient',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: ['approvals'],
    requiredEvidenceKinds: ['approval_provenance_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Not enough valid approvals are bound to the proposed consequence.',
  },
  {
    reasonCode: 'approval-review',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: ['approvals'],
    requiredEvidenceKinds: ['approval_provenance_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance requires customer or operator review.',
  },
  {
    reasonCode: 'approval-block',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['approvals'],
    requiredEvidenceKinds: ['approval_provenance_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Approval provenance failed closed.',
  },
  {
    reasonCode: 'narrow-required',
    audience: 'model',
    disclosureLevel: 'actionable',
    missingFields: [],
    requiredEvidenceKinds: ['narrowing_ref'],
    retryableByModel: true,
    operatorOnly: false,
    safeSummary: 'Retry only with a narrower customer-approved consequence scope.',
  },
  {
    reasonCode: 'adapter-readiness-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['observedFeatures.adapterReady'],
    requiredEvidenceKinds: ['adapter_readiness_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Adapter readiness is an operator or customer integration control.',
  },
  {
    reasonCode: 'adapter-readiness-origin-untrusted',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['observedFeatureOrigins.adapterReady'],
    requiredEvidenceKinds: ['adapter_readiness_origin_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Adapter readiness must be attested by an operator, customer gateway, Attestor runtime, or trusted adapter.',
  },
  {
    reasonCode: 'custom-domain-review-required',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: ['customer_policy_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Custom consequence domains require customer policy review before automation.',
  },
  {
    reasonCode: 'hold-ledger-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['noGoConditions'],
    requiredEvidenceKinds: ['no_go_condition_ledger_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'No-go condition state must be supplied by the customer or operator boundary.',
  },
  {
    reasonCode: 'active-no-go-condition-present',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: ['no_go_condition_release_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'An active no-go condition blocks automatic execution.',
  },
  {
    reasonCode: 'pending-hold-review-required',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: ['no_go_condition_review_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'A pending no-go hold requires customer or operator review.',
  },
  {
    reasonCode: 'hold-owner-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['noGoConditions.ownerRef'],
    requiredEvidenceKinds: ['no_go_hold_owner_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'No-go hold records must bind to a responsible owner.',
  },
  {
    reasonCode: 'hold-authority-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['noGoConditions.ownerAuthorityDigest'],
    requiredEvidenceKinds: ['no_go_hold_authority_digest'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'No-go hold records must bind to owner authority evidence.',
  },
  {
    reasonCode: 'hold-validity-missing',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['noGoConditions.issuedAt', 'noGoConditions.expiresAt'],
    requiredEvidenceKinds: ['no_go_hold_validity_window'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'No-go hold records must include a bounded validity window.',
  },
  {
    reasonCode: 'hold-issued-at-invalid',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['noGoConditions.issuedAt'],
    requiredEvidenceKinds: ['no_go_hold_validity_window'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'No-go hold issued-at timestamps must be valid.',
  },
  {
    reasonCode: 'hold-expires-at-invalid',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['noGoConditions.expiresAt'],
    requiredEvidenceKinds: ['no_go_hold_validity_window'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'No-go hold expiry timestamps must be valid.',
  },
  {
    reasonCode: 'untrusted-hold-source',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: ['noGoConditions.sourceKind'],
    requiredEvidenceKinds: ['trusted_no_go_hold_source_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Untrusted content cannot create or release a no-go hold.',
  },
  {
    reasonCode: 'natural-language-bypass-attempted',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: ['no_go_bypass_review_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'A natural-language attempt to bypass a no-go hold blocks automatic execution.',
  },
  {
    reasonCode: 'natural-language-bypass-inferred',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: ['no_go_bypass_review_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'Detected no-go bypass language must be reviewed outside the model loop.',
  },
  {
    reasonCode: 'no-go-condition-review',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: ['no_go_condition_review_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'No-go condition state requires customer or operator review.',
  },
  {
    reasonCode: 'no-go-condition-block',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: ['no_go_condition_release_ref'],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'No-go condition state blocks automatic execution.',
  },
  {
    reasonCode: 'policy-blocked',
    audience: 'customer-review',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: [],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'The customer policy blocked the proposed consequence.',
  },
  {
    reasonCode: 'feature-blocked',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: [],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'A customer or operator supplied blocked signal prevented automatic retry.',
  },
  {
    reasonCode: 'feature-unsafe',
    audience: 'operator-control',
    disclosureLevel: 'minimal',
    missingFields: [],
    requiredEvidenceKinds: [],
    retryableByModel: false,
    operatorOnly: true,
    safeSummary: 'A customer or operator supplied unsafe signal prevented automatic retry.',
  },
]);
