import {
  CONSEQUENCE_ADMISSION_ADAPTER_KINDS,
  CONSEQUENCE_ADMISSION_ADAPTER_OUTCOMES,
} from './adapter-framework.js';
import {
  CONSEQUENCE_ADMISSION_AGENT_LOOP_ABUSE_GUARD_OUTCOMES,
  CONSEQUENCE_ADMISSION_AGENT_LOOP_ABUSE_GUARD_REASON_CODES,
  CONSEQUENCE_ADMISSION_AGENT_LOOP_ABUSE_GUARD_VERSION,
} from './agent-loop-abuse-guard.js';
import {
  CONSEQUENCE_AGENTIC_SUPPLY_CHAIN_GUARD_OUTCOMES,
  CONSEQUENCE_AGENTIC_SUPPLY_CHAIN_GUARD_VERSION,
  CONSEQUENCE_AGENTIC_SUPPLY_CHAIN_REASON_CODES,
} from './agentic-supply-chain-guard.js';
import {
  CONSEQUENCE_AUDIT_EVIDENCE_ARTIFACT_KINDS,
  CONSEQUENCE_AUDIT_EVIDENCE_FINDING_KINDS,
} from './audit-evidence-export.js';
import {
  AUTHORITY_CREEP_FINDINGS,
  AUTHORITY_CREEP_GUARD_VERSION,
  AUTHORITY_CREEP_OUTCOMES,
} from './authority-creep-guard.js';
import {
  CONSEQUENCE_BUSINESS_RISK_DASHBOARD_WIDGETS,
  CONSEQUENCE_BUSINESS_RISK_SIGNALS,
} from './business-risk-dashboard.js';
import {
  CONSEQUENCE_ADMISSION_CONSTRAINT_KINDS,
} from './constraint-kinds.js';
import {
  CONSEQUENCE_ADMISSION_CHECK_KINDS,
  CONSEQUENCE_ADMISSION_CHECK_OUTCOMES,
  CONSEQUENCE_ADMISSION_CONSEQUENCE_KINDS,
  CONSEQUENCE_ADMISSION_CONTRACT_VERSION,
  CONSEQUENCE_ADMISSION_CORRECTION_AUDIENCES,
  CONSEQUENCE_ADMISSION_CORRECTION_CATALOG_VERSION,
  CONSEQUENCE_ADMISSION_DECISIONS,
  CONSEQUENCE_ADMISSION_ENTRY_POINT_KINDS,
  CONSEQUENCE_ADMISSION_FEEDBACK_DISCLOSURE_LEVELS,
  CONSEQUENCE_ADMISSION_NATIVE_SURFACES,
  CONSEQUENCE_ADMISSION_PACK_FAMILIES,
  CONSEQUENCE_ADMISSION_PROOF_KINDS,
  CONSEQUENCE_ADMISSION_RETRY_ATTEMPT_VERSION,
  CONSEQUENCE_ADMISSION_RETRY_BINDING_FIELDS,
  CONSEQUENCE_ADMISSION_RETRY_BUDGET_OUTCOMES,
  CONSEQUENCE_ADMISSION_RETRY_DEFAULT_MAX_ATTEMPTS,
  CONSEQUENCE_ADMISSION_RETRY_DEFAULT_WINDOW_SECONDS,
  CONSEQUENCE_ADMISSION_RETRY_RULE_VERSION,
  CONSEQUENCE_ADMISSION_RISK_CLASSES,
  GENERIC_ADMISSION_DOWNSTREAM_POSTURES,
  GENERIC_ADMISSION_MODES,
  GENERIC_ADMISSION_OBSERVED_FEATURE_ORIGINS,
  GENERIC_ADMISSION_SHADOW_DECISIONS,
  type ConsequenceAdmissionDescriptor,
} from './contracts.js';
import {
  ATTESTOR_CONTROL_PLANE_ROLES,
  ATTESTOR_CONTROL_PLANE_ROLE_DESCRIPTORS,
  ATTESTOR_CONTROL_PLANE_ROLE_VERSION,
} from './control-plane-roles.js';
import {
  consequenceAdmissionCorrectionCatalog,
} from './correction-catalog.js';
import {
  CUSTOMER_PEP_ADOPTION_PACKAGE_VERSION,
  customerPepAdoptionPackageDescriptor,
} from './customer-pep-adoption-package.js';
import {
  CUSTOMER_PEP_RUNTIME_ADOPTION_VERSION,
  customerPepRuntimeAdoptionDescriptor,
} from './customer-pep-runtime-adoption.js';
import {
  CONSEQUENCE_DASHBOARD_API_SUMMARY_ATTENTION_KINDS,
  CONSEQUENCE_DASHBOARD_API_SUMMARY_LINK_KINDS,
  CONSEQUENCE_DASHBOARD_API_SUMMARY_TILE_KINDS,
} from './dashboard-api-summary.js';
import {
  ATTESTOR_REVIEW_SURFACE_AREAS,
  ATTESTOR_REVIEW_SURFACE_CONTRACT_SLICES,
  ATTESTOR_REVIEW_SURFACE_DATA_FORMS,
  ATTESTOR_REVIEW_SURFACE_FRESHNESS_STATES,
  ATTESTOR_REVIEW_SURFACE_LIFECYCLE_STATES,
  ATTESTOR_REVIEW_SURFACE_STATUS_LABELS,
  ATTESTOR_REVIEW_SURFACE_VERSION,
} from './attestor-review-surface-contract.js';
import {
  CONSEQUENCE_DATA_MINIMIZATION_FORBIDDEN_RAW_CLASSES,
  CONSEQUENCE_DATA_MINIMIZATION_REDACTION_POLICY_VERSION,
  CONSEQUENCE_DATA_MINIMIZATION_SURFACE_KINDS,
} from './data-minimization-redaction-policy.js';
import {
  CONSEQUENCE_DECISION_CONTEXT_DRIFT_BINDING_VERSION,
  CONSEQUENCE_DECISION_CONTEXT_DRIFT_OUTCOMES,
  CONSEQUENCE_DECISION_CONTEXT_DRIFT_REASON_CODES,
} from './decision-context-drift-binding.js';
import {
  CONSEQUENCE_DOMAIN_PACK_BOUNDARY_VERSION,
  consequenceDomainPackBoundaryDescriptor,
} from './domain-pack-boundary.js';
import {
  CONSEQUENCE_ADMISSION_DOWNSTREAM_EXECUTION_STATUSES,
} from './downstream-execution-receipt.js';
import {
  CONSEQUENCE_EXTERNAL_REVIEW_EVIDENCE_KINDS,
  CONSEQUENCE_EXTERNAL_REVIEW_EVIDENCE_STATUSES,
  CONSEQUENCE_EXTERNAL_REVIEW_FINDING_KINDS,
  CONSEQUENCE_EXTERNAL_REVIEW_FOCUS_AREAS,
} from './external-review-packet.js';
import {
  CONSEQUENCE_FAILURE_MODE_GUARD_COVERAGE_VERSION,
  consequenceFailureModeGuardCoverageMatrix,
} from './failure-mode-guard-coverage.js';
import {
  CONSEQUENCE_FAILURE_MODE_REGISTRY_PLACEMENT_VERSION,
  consequenceFailureModeRegistryPlacementDescriptor,
} from './failure-mode-registry.js';
import {
  CONSEQUENCE_FAILURE_MODE_RUNTIME_EXTENSION_OUTCOMES,
  CONSEQUENCE_FAILURE_MODE_RUNTIME_EXTENSION_REASON_CODES,
  CONSEQUENCE_FAILURE_MODE_RUNTIME_EXTENSION_VERSION,
} from './failure-mode-runtime-extensions.js';
import {
  CONSEQUENCE_GUARD_ACTIVATION_READINESS_VERSION,
  consequenceGuardActivationReadinessDescriptor,
} from './guard-activation-readiness.js';
import {
  CONSEQUENCE_HUMAN_REVIEW_FATIGUE_GUARD_VERSION,
  CONSEQUENCE_HUMAN_REVIEW_FATIGUE_OUTCOMES,
  CONSEQUENCE_HUMAN_REVIEW_FATIGUE_REASON_CODES,
} from './human-review-fatigue-guard.js';
import {
  CONSEQUENCE_MULTI_AGENT_DELEGATION_GUARD_OUTCOMES,
  CONSEQUENCE_MULTI_AGENT_DELEGATION_GUARD_VERSION,
  CONSEQUENCE_MULTI_AGENT_DELEGATION_REASON_CODES,
} from './multi-agent-delegation-guard.js';
import {
  CONSEQUENCE_ADMISSION_PACK_DECISION_POSTURES,
  CONSEQUENCE_ADMISSION_PACK_DECISION_PROFILE_VERSION,
  CONSEQUENCE_ADMISSION_PACK_DECISION_RECOMMENDED_ACTIONS,
  CONSEQUENCE_ADMISSION_PACK_DECISION_SIGNAL_KINDS,
} from './pack-decision-profile.js';
import {
  CONSEQUENCE_ADMISSION_POLICY_LIMIT_BREACH_ACTIONS,
  CONSEQUENCE_ADMISSION_POLICY_LIMIT_KINDS,
} from './policy-limits.js';
import {
  CONSEQUENCE_ADMISSION_PRESENTATION_BINDING_FIELDS,
} from './presentation-binding.js';
import {
  CONSEQUENCE_ADMISSION_PRESENTATION_REPLAY_LEDGER_FAILURE_REASONS,
} from './presentation-replay-ledger.js';
import {
  PROTECTED_ADMISSION_E2E_PROOF_PLAN_VERSION,
  protectedAdmissionE2eProofPlanDescriptor,
} from './protected-admission-e2e-proof-plan.js';
import {
  CONSEQUENCE_REPLAY_LAYER_PLACEMENT_VERSION,
  consequenceReplayLayerPlacementDescriptor,
} from './replay-layer-placement.js';
import {
  CONSEQUENCE_ADMISSION_RETRY_ATTEMPT_LEDGER_FAILURE_REASONS,
  CONSEQUENCE_ADMISSION_RETRY_ATTEMPT_LEDGER_OUTCOMES,
  CONSEQUENCE_ADMISSION_RETRY_ATTEMPT_LEDGER_VERSION,
} from './retry-attempt-ledger.js';
import {
  CONSEQUENCE_SHADOW_READINESS_CLAIM_ALIGNMENT_VERSION,
  consequenceShadowReadinessClaimAlignmentDescriptor,
} from './shadow-readiness-claim-alignment.js';
import {
  CONSEQUENCE_TAMPER_EVIDENT_HISTORY_ENTRY_KINDS,
  CONSEQUENCE_TAMPER_EVIDENT_HISTORY_VERIFICATION_FAILURE_REASONS,
  CONSEQUENCE_TAMPER_EVIDENT_HISTORY_VERSION,
} from './tamper-evident-history.js';
import {
  CONSEQUENCE_ADMISSION_CONTROL_REQUIREMENTS,
  CONSEQUENCE_ADMISSION_DOMAINS,
  CONSEQUENCE_ADMISSION_TAXONOMY,
} from './taxonomy.js';

export function consequenceAdmissionDescriptor():
ConsequenceAdmissionDescriptor {
  return Object.freeze({
    version: CONSEQUENCE_ADMISSION_CONTRACT_VERSION,
    retryAttemptVersion: CONSEQUENCE_ADMISSION_RETRY_ATTEMPT_VERSION,
    retryRuleVersion: CONSEQUENCE_ADMISSION_RETRY_RULE_VERSION,
    retryAttemptLedgerVersion: CONSEQUENCE_ADMISSION_RETRY_ATTEMPT_LEDGER_VERSION,
    agentLoopAbuseGuardVersion: CONSEQUENCE_ADMISSION_AGENT_LOOP_ABUSE_GUARD_VERSION,
    correctionCatalogVersion: CONSEQUENCE_ADMISSION_CORRECTION_CATALOG_VERSION,
    dataMinimizationPolicyVersion: CONSEQUENCE_DATA_MINIMIZATION_REDACTION_POLICY_VERSION,
    packDecisionProfileVersion: CONSEQUENCE_ADMISSION_PACK_DECISION_PROFILE_VERSION,
    domainPackBoundaryVersion: CONSEQUENCE_DOMAIN_PACK_BOUNDARY_VERSION,
    controlPlaneRoleVersion: ATTESTOR_CONTROL_PLANE_ROLE_VERSION,
    failureModeRegistryPlacementVersion: CONSEQUENCE_FAILURE_MODE_REGISTRY_PLACEMENT_VERSION,
    replayLayerPlacementVersion: CONSEQUENCE_REPLAY_LAYER_PLACEMENT_VERSION,
    guardActivationReadinessVersion: CONSEQUENCE_GUARD_ACTIVATION_READINESS_VERSION,
    shadowReadinessClaimAlignmentVersion:
      CONSEQUENCE_SHADOW_READINESS_CLAIM_ALIGNMENT_VERSION,
    failureModeGuardCoverageVersion: CONSEQUENCE_FAILURE_MODE_GUARD_COVERAGE_VERSION,
    failureModeRuntimeExtensionVersion: CONSEQUENCE_FAILURE_MODE_RUNTIME_EXTENSION_VERSION,
    customerPepRuntimeAdoptionVersion: CUSTOMER_PEP_RUNTIME_ADOPTION_VERSION,
    customerPepAdoptionPackageVersion: CUSTOMER_PEP_ADOPTION_PACKAGE_VERSION,
    protectedAdmissionE2eProofPlanVersion: PROTECTED_ADMISSION_E2E_PROOF_PLAN_VERSION,
    agenticSupplyChainGuardVersion: CONSEQUENCE_AGENTIC_SUPPLY_CHAIN_GUARD_VERSION,
    humanReviewFatigueGuardVersion: CONSEQUENCE_HUMAN_REVIEW_FATIGUE_GUARD_VERSION,
    decisionContextDriftBindingVersion:
      CONSEQUENCE_DECISION_CONTEXT_DRIFT_BINDING_VERSION,
    multiAgentDelegationGuardVersion: CONSEQUENCE_MULTI_AGENT_DELEGATION_GUARD_VERSION,
    authorityCreepGuardVersion: AUTHORITY_CREEP_GUARD_VERSION,
    retryDefaultMaxAttempts: CONSEQUENCE_ADMISSION_RETRY_DEFAULT_MAX_ATTEMPTS,
    retryDefaultWindowSeconds: CONSEQUENCE_ADMISSION_RETRY_DEFAULT_WINDOW_SECONDS,
    decisions: CONSEQUENCE_ADMISSION_DECISIONS,
    genericAdmissionModes: GENERIC_ADMISSION_MODES,
    genericAdmissionObservedFeatureOrigins: GENERIC_ADMISSION_OBSERVED_FEATURE_ORIGINS,
    genericAdmissionShadowDecisions: GENERIC_ADMISSION_SHADOW_DECISIONS,
    genericAdmissionDownstreamPostures: GENERIC_ADMISSION_DOWNSTREAM_POSTURES,
    packFamilies: CONSEQUENCE_ADMISSION_PACK_FAMILIES,
    consequenceKinds: CONSEQUENCE_ADMISSION_CONSEQUENCE_KINDS,
    riskClasses: CONSEQUENCE_ADMISSION_RISK_CLASSES,
    entryPointKinds: CONSEQUENCE_ADMISSION_ENTRY_POINT_KINDS,
    checkKinds: CONSEQUENCE_ADMISSION_CHECK_KINDS,
    checkOutcomes: CONSEQUENCE_ADMISSION_CHECK_OUTCOMES,
    feedbackDisclosureLevels: CONSEQUENCE_ADMISSION_FEEDBACK_DISCLOSURE_LEVELS,
    correctionAudiences: CONSEQUENCE_ADMISSION_CORRECTION_AUDIENCES,
    correctionReasonCodes: consequenceAdmissionCorrectionCatalog().reasonCodes,
    controlPlaneRoles: ATTESTOR_CONTROL_PLANE_ROLES,
    controlPlaneRoleDescriptors: ATTESTOR_CONTROL_PLANE_ROLE_DESCRIPTORS,
    domainPackBoundary: consequenceDomainPackBoundaryDescriptor(),
    failureModeRegistryPlacement: consequenceFailureModeRegistryPlacementDescriptor(),
    replayLayerPlacement: consequenceReplayLayerPlacementDescriptor(),
    guardActivationReadiness: consequenceGuardActivationReadinessDescriptor(),
    shadowReadinessClaimAlignment: consequenceShadowReadinessClaimAlignmentDescriptor(),
    failureModeGuardCoverage: consequenceFailureModeGuardCoverageMatrix(),
    customerPepRuntimeAdoption: customerPepRuntimeAdoptionDescriptor(),
    customerPepAdoptionPackage: customerPepAdoptionPackageDescriptor(),
    protectedAdmissionE2eProofPlan: protectedAdmissionE2eProofPlanDescriptor(),
    dataMinimizationSurfaceKinds: CONSEQUENCE_DATA_MINIMIZATION_SURFACE_KINDS,
    dataMinimizationForbiddenRawClasses: CONSEQUENCE_DATA_MINIMIZATION_FORBIDDEN_RAW_CLASSES,
    packDecisionPostures: CONSEQUENCE_ADMISSION_PACK_DECISION_POSTURES,
    packDecisionRecommendedActions: CONSEQUENCE_ADMISSION_PACK_DECISION_RECOMMENDED_ACTIONS,
    packDecisionSignalKinds: CONSEQUENCE_ADMISSION_PACK_DECISION_SIGNAL_KINDS,
    retryBindingFields: CONSEQUENCE_ADMISSION_RETRY_BINDING_FIELDS,
    retryBudgetOutcomes: CONSEQUENCE_ADMISSION_RETRY_BUDGET_OUTCOMES,
    retryAttemptLedgerOutcomes: CONSEQUENCE_ADMISSION_RETRY_ATTEMPT_LEDGER_OUTCOMES,
    retryAttemptLedgerFailureReasons: CONSEQUENCE_ADMISSION_RETRY_ATTEMPT_LEDGER_FAILURE_REASONS,
    agentLoopAbuseGuardOutcomes: CONSEQUENCE_ADMISSION_AGENT_LOOP_ABUSE_GUARD_OUTCOMES,
    agentLoopAbuseGuardReasonCodes: CONSEQUENCE_ADMISSION_AGENT_LOOP_ABUSE_GUARD_REASON_CODES,
    adapterKinds: CONSEQUENCE_ADMISSION_ADAPTER_KINDS,
    adapterOutcomes: CONSEQUENCE_ADMISSION_ADAPTER_OUTCOMES,
    agenticSupplyChainGuardOutcomes: CONSEQUENCE_AGENTIC_SUPPLY_CHAIN_GUARD_OUTCOMES,
    agenticSupplyChainGuardReasonCodes: CONSEQUENCE_AGENTIC_SUPPLY_CHAIN_REASON_CODES,
    humanReviewFatigueGuardOutcomes: CONSEQUENCE_HUMAN_REVIEW_FATIGUE_OUTCOMES,
    humanReviewFatigueGuardReasonCodes: CONSEQUENCE_HUMAN_REVIEW_FATIGUE_REASON_CODES,
    decisionContextDriftOutcomes: CONSEQUENCE_DECISION_CONTEXT_DRIFT_OUTCOMES,
    decisionContextDriftReasonCodes: CONSEQUENCE_DECISION_CONTEXT_DRIFT_REASON_CODES,
    multiAgentDelegationGuardOutcomes: CONSEQUENCE_MULTI_AGENT_DELEGATION_GUARD_OUTCOMES,
    multiAgentDelegationGuardReasonCodes: CONSEQUENCE_MULTI_AGENT_DELEGATION_REASON_CODES,
    authorityCreepGuardOutcomes: AUTHORITY_CREEP_OUTCOMES,
    authorityCreepGuardFindings: AUTHORITY_CREEP_FINDINGS,
    failureModeRuntimeExtensionOutcomes: CONSEQUENCE_FAILURE_MODE_RUNTIME_EXTENSION_OUTCOMES,
    failureModeRuntimeExtensionReasonCodes: CONSEQUENCE_FAILURE_MODE_RUNTIME_EXTENSION_REASON_CODES,
    auditEvidenceArtifactKinds: CONSEQUENCE_AUDIT_EVIDENCE_ARTIFACT_KINDS,
    auditEvidenceFindingKinds: CONSEQUENCE_AUDIT_EVIDENCE_FINDING_KINDS,
    tamperEvidentHistoryVersion: CONSEQUENCE_TAMPER_EVIDENT_HISTORY_VERSION,
    tamperEvidentHistoryEntryKinds: CONSEQUENCE_TAMPER_EVIDENT_HISTORY_ENTRY_KINDS,
    tamperEvidentHistoryVerificationFailureReasons:
      CONSEQUENCE_TAMPER_EVIDENT_HISTORY_VERIFICATION_FAILURE_REASONS,
    businessRiskDashboardWidgets: CONSEQUENCE_BUSINESS_RISK_DASHBOARD_WIDGETS,
    businessRiskSignals: CONSEQUENCE_BUSINESS_RISK_SIGNALS,
    dashboardApiSummaryTileKinds: CONSEQUENCE_DASHBOARD_API_SUMMARY_TILE_KINDS,
    dashboardApiSummaryAttentionKinds: CONSEQUENCE_DASHBOARD_API_SUMMARY_ATTENTION_KINDS,
    dashboardApiSummaryLinkKinds: CONSEQUENCE_DASHBOARD_API_SUMMARY_LINK_KINDS,
    reviewSurfaceVersion: ATTESTOR_REVIEW_SURFACE_VERSION,
    reviewSurfaceAreas: ATTESTOR_REVIEW_SURFACE_AREAS,
    reviewSurfaceDataForms: ATTESTOR_REVIEW_SURFACE_DATA_FORMS,
    reviewSurfaceContractSlices: ATTESTOR_REVIEW_SURFACE_CONTRACT_SLICES,
    reviewSurfaceFreshnessStates: ATTESTOR_REVIEW_SURFACE_FRESHNESS_STATES,
    reviewSurfaceLifecycleStates: ATTESTOR_REVIEW_SURFACE_LIFECYCLE_STATES,
    reviewSurfaceStatusLabels: ATTESTOR_REVIEW_SURFACE_STATUS_LABELS,
    externalReviewFocusAreas: CONSEQUENCE_EXTERNAL_REVIEW_FOCUS_AREAS,
    externalReviewEvidenceKinds: CONSEQUENCE_EXTERNAL_REVIEW_EVIDENCE_KINDS,
    externalReviewEvidenceStatuses: CONSEQUENCE_EXTERNAL_REVIEW_EVIDENCE_STATUSES,
    externalReviewFindingKinds: CONSEQUENCE_EXTERNAL_REVIEW_FINDING_KINDS,
    proofKinds: CONSEQUENCE_ADMISSION_PROOF_KINDS,
    nativeSurfaces: CONSEQUENCE_ADMISSION_NATIVE_SURFACES,
    consequenceDomains: CONSEQUENCE_ADMISSION_DOMAINS,
    controlRequirements: CONSEQUENCE_ADMISSION_CONTROL_REQUIREMENTS,
    taxonomy: CONSEQUENCE_ADMISSION_TAXONOMY,
    policyLimitKinds: CONSEQUENCE_ADMISSION_POLICY_LIMIT_KINDS,
    policyLimitBreachActions: CONSEQUENCE_ADMISSION_POLICY_LIMIT_BREACH_ACTIONS,
    constraintKinds: CONSEQUENCE_ADMISSION_CONSTRAINT_KINDS,
    presentationBindingFields: CONSEQUENCE_ADMISSION_PRESENTATION_BINDING_FIELDS,
    presentationReplayLedgerFailureReasons: CONSEQUENCE_ADMISSION_PRESENTATION_REPLAY_LEDGER_FAILURE_REASONS,
    downstreamExecutionStatuses: CONSEQUENCE_ADMISSION_DOWNSTREAM_EXECUTION_STATUSES,
  });
}
