import {
  createRecipe,
  REQUIRED_NORMALIZED_FIELDS,
} from './domain-consequence-recipes-utils.js';
import type { DomainConsequenceRecipe } from './domain-consequence-recipes-types.js';

const BASE_NORMALIZED_FIELDS = Object.freeze([
  ...REQUIRED_NORMALIZED_FIELDS,
  'amountRefDigest',
  'payeeRefDigest',
  'dataClassRefDigest',
  'authorityDeltaRefDigest',
  'clinicalOrClaimContextDigest',
  'policyCandidateDigest',
]);

const BASE_APPROVAL_PATH = Object.freeze([
  'review-by-exception item',
  'approval/dismiss feedback event',
  'customer-owned approval or exception queue',
]);

const BASE_IMPLEMENTATION_STEPS = Object.freeze([
  'normalize the proposed consequence into digest-only fields',
  'call Attestor before the target side effect',
  'hold on review or block until customer approval resolves the gap',
  'return a downstream receipt digest after customer-owned execution',
]);

export const RECIPES = Object.freeze([
  createRecipe({
    recipeId: 'domain:ramp-spend-accounting',
    targetSystem: 'ramp-spend-accounting',
    targetFamily: 'spend-procurement',
    displayName: 'Ramp spend and accounting API',
    primarySourceName: 'Ramp API documentation',
    primarySourceUrl: 'https://docs.ramp.com/llms-api.txt',
    pattern: 'spend-request-gate',
    readiness: 'requires-target-design',
    insertionPoint: 'Before Ramp bill, reimbursement, transaction sync, vendor, GL account, or custom field write is marked ready or synchronized.',
    attestorPlacement: 'Attestor receives digest-only spend request, vendor, accounting field, amount, and approval refs before the customer-owned Ramp integration writes or syncs.',
    protectedConsequences: Object.freeze([
      'bill.payment.prepare',
      'reimbursement.approve',
      'vendor.update',
      'transaction.ready_to_sync',
      'gl_account.update',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'invoice-or-receipt digest',
      'vendor verification digest',
      'budget or cost-center digest',
      'approval-chain digest',
      'idempotency key digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'Ramp object id digest',
      'sync result digest',
      'accounting reference digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'request id digest',
      'idempotency key digest',
      'sync attempt digest',
    ]),
    riskSignals: Object.freeze([
      'new vendor',
      'changed remittance detail',
      'amount above policy',
      'missing receipt',
      'manual GL override',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No Ramp app, partner certification, live API token, vendor record ownership, payment execution, or accounting system ownership is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:brex-expenses-api',
    targetSystem: 'brex-expenses-api',
    targetFamily: 'spend-procurement',
    displayName: 'Brex Expenses API',
    primarySourceName: 'Brex Expenses API',
    primarySourceUrl: 'https://developer.brex.com/openapi/expenses_api/',
    pattern: 'spend-request-gate',
    readiness: 'requires-target-design',
    insertionPoint: 'Before a customer-owned Brex integration updates expense data, uploads receipt material, or exports expense state.',
    attestorPlacement: 'Attestor receives digest-only expense, receipt, policy, merchant, amount, and reviewer refs before the customer-owned Brex API caller proceeds.',
    protectedConsequences: Object.freeze([
      'expense.update',
      'receipt.upload',
      'receipt.match',
      'expense.export',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'receipt digest',
      'merchant digest',
      'expense policy digest',
      'card transaction digest',
      'reviewer decision digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'Brex expense id digest',
      'receipt upload receipt digest',
      'expense export receipt digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'expense id digest',
      'receipt id digest',
      'export attempt digest',
    ]),
    riskSignals: Object.freeze([
      'missing receipt',
      'policy exception',
      'merchant mismatch',
      'duplicate expense',
      'manual amount change',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No Brex app, live API token, expense system ownership, card control, payment execution, or accounting sync ownership is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:coupa-approvals',
    targetSystem: 'coupa-approvals',
    targetFamily: 'spend-procurement',
    displayName: 'Coupa approvals',
    primarySourceName: 'Coupa Approvals API',
    primarySourceUrl: 'https://docs.coupa.com/en/developer-documentation/the-coupa-core-api/resources/transactional-resources/approvals-api-approvals',
    pattern: 'procurement-approval-gate',
    readiness: 'recipe-ready',
    insertionPoint: 'Before a customer-owned Coupa API client creates, updates, or queries approval state for a procurement document.',
    attestorPlacement: 'Attestor receives digest-only document, supplier, amount, requester, approver, and policy refs before the Coupa approval mutation proceeds.',
    protectedConsequences: Object.freeze([
      'purchase_order.approve',
      'invoice.approve',
      'supplier.change.approve',
      'approval.update',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'purchase order digest',
      'supplier digest',
      'budget digest',
      'approval chain digest',
      'segregation-of-duties digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'Coupa approval id digest',
      'document state digest',
      'approver receipt digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'document id digest',
      'approval id digest',
      'approval transition digest',
    ]),
    riskSignals: Object.freeze([
      'new supplier',
      'bank detail change',
      'amount above threshold',
      'approver conflict',
      'missing purchase order evidence',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No Coupa native connector, buyer record ownership, supplier master ownership, or procurement workflow replacement is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:sap-s4hana-purchase-order',
    targetSystem: 'sap-s4hana-purchase-order',
    targetFamily: 'spend-procurement',
    displayName: 'SAP S/4HANA purchase order',
    primarySourceName: 'SAP S/4HANA Purchase Order - Send, Update, Cancel',
    primarySourceUrl: 'https://help.sap.com/docs/SAP_S4HANA_CLOUD/bb9f1469daf04bd894ab2167f8132a1a/fd5b4bdc2e7147429cb2de044ccbd890.html',
    pattern: 'procurement-approval-gate',
    readiness: 'recipe-ready',
    insertionPoint: 'Before a customer-owned SAP integration sends, updates, cancels, or publishes a purchase order to a supplier network.',
    attestorPlacement: 'Attestor receives digest-only purchase order, supplier, item, amount, tax, and approval refs before the SAP-side operation is invoked.',
    protectedConsequences: Object.freeze([
      'purchase_order.send',
      'purchase_order.update',
      'purchase_order.cancel',
      'supplier_network.publish',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'purchase order digest',
      'supplier digest',
      'item and tax digest',
      'budget or project digest',
      'approval chain digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'SAP purchase order id digest',
      'supplier network message digest',
      'change document digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'purchase order id digest',
      'operation id digest',
      'supplier message digest',
    ]),
    riskSignals: Object.freeze([
      'supplier change',
      'tax condition change',
      'cancel operation',
      'new item category',
      'amount above policy',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No SAP app, SAP Business Network integration, purchase order ownership, supplier master ownership, or ERP workflow replacement is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:snowflake-cortex-agents',
    targetSystem: 'snowflake-cortex-agents',
    targetFamily: 'data-ai-platform',
    displayName: 'Snowflake Cortex Agents',
    primarySourceName: 'Snowflake Cortex Agents REST API',
    primarySourceUrl: 'https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-agents-rest-api',
    pattern: 'data-tool-gate',
    readiness: 'recipe-ready',
    insertionPoint: 'Before Cortex Agent SQL execution, generic tool invocation, external function call, export, or publish path performs a data side effect.',
    attestorPlacement: 'Attestor receives digest-only semantic model, warehouse, role, tool, query class, data class, and approval refs before the customer-owned Snowflake operation proceeds.',
    protectedConsequences: Object.freeze([
      'sql.execute.write',
      'customer.export',
      'external_function.call',
      'semantic.query.publish',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'semantic model digest',
      'warehouse and role digest',
      'data classification digest',
      'query class digest',
      'export approval digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'Snowflake request id digest',
      'query or job receipt digest',
      'export receipt digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'agent request digest',
      'query fingerprint digest',
      'warehouse execution digest',
    ]),
    riskSignals: Object.freeze([
      'write query',
      'external function call',
      'large export',
      'sensitive data class',
      'auto execute SQL tool',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No Snowflake deployment, warehouse ownership, data lake, query executor, or data export service is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:databricks-agent-tools',
    targetSystem: 'databricks-agent-tools',
    targetFamily: 'data-ai-platform',
    displayName: 'Databricks AI agent tools',
    primarySourceName: 'Databricks AI agent tools',
    primarySourceUrl: 'https://docs.databricks.com/aws/en/generative-ai/agent-framework/agent-tool',
    pattern: 'data-tool-gate',
    readiness: 'recipe-ready',
    insertionPoint: 'Before a Databricks agent tool runs a Unity Catalog function, custom code tool, REST/API tool, MCP tool, job, or export side effect.',
    attestorPlacement: 'Attestor receives digest-only workspace, tool, Unity Catalog object, job, data class, and approval refs before the customer-owned Databricks tool call proceeds.',
    protectedConsequences: Object.freeze([
      'uc.function.execute',
      'workspace.job.run',
      'rest.tool.call',
      'data.export',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'Unity Catalog function digest',
      'workspace and cluster digest',
      'tool schema digest',
      'data classification digest',
      'job or export approval digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'Databricks trace digest',
      'job run digest',
      'tool result receipt digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'tool call digest',
      'function invocation digest',
      'job run digest',
    ]),
    riskSignals: Object.freeze([
      'custom code execution',
      'external API call',
      'data export',
      'job run',
      'sensitive catalog object',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No Databricks app, workspace ownership, Unity Catalog administration, job runner, or data export service is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:okta-workflows-authority',
    targetSystem: 'okta-workflows-authority',
    targetFamily: 'iam-authority',
    displayName: 'Okta Workflows authority changes',
    primarySourceName: 'Okta Workflows Okta connector',
    primarySourceUrl: 'https://help.okta.com/wf/en-us/Content/Topics/Workflows/connector-reference/okta/okta.htm',
    pattern: 'identity-workflow-gate',
    readiness: 'recipe-ready',
    insertionPoint: 'Before Okta Workflows user, group, application, policy, OAuth consent, or privilege action cards create an authority change.',
    attestorPlacement: 'Attestor receives digest-only user, group, app, policy, privilege, requester, and approval refs before the customer-owned Okta workflow proceeds.',
    protectedConsequences: Object.freeze([
      'group.add_user',
      'app.assign_user',
      'policy.rule.activate',
      'user.privilege.grant',
      'oauth.consent.grant',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'identity digest',
      'group or app digest',
      'access request digest',
      'approval decision digest',
      'separation-of-duties digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'Okta workflow execution digest',
      'system log event digest',
      'connector action receipt digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'workflow execution digest',
      'target authority digest',
      'access request digest',
    ]),
    riskSignals: Object.freeze([
      'privileged group',
      'admin privilege grant',
      'policy activation',
      'OAuth consent grant',
      'break-glass account',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No Okta connector, identity store ownership, policy ownership, or lifecycle workflow ownership is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:microsoft-entra-lifecycle-workflows',
    targetSystem: 'microsoft-entra-lifecycle-workflows',
    targetFamily: 'iam-authority',
    displayName: 'Microsoft Entra Lifecycle Workflows',
    primarySourceName: 'Microsoft Entra workflow extensibility',
    primarySourceUrl: 'https://learn.microsoft.com/en-us/entra/id-governance/lifecycle-workflow-extensibility',
    pattern: 'identity-workflow-gate',
    readiness: 'recipe-ready',
    insertionPoint: 'Before an Entra Lifecycle Workflow custom task extension or Logic App continues an access, lifecycle, or group-membership side effect.',
    attestorPlacement: 'Attestor receives digest-only lifecycle workflow, user, access package, group, task extension, and approval refs before the customer-owned Logic App continues.',
    protectedConsequences: Object.freeze([
      'lifecycle.continue',
      'access.assign',
      'group.membership.update',
      'user.lifecycle.change',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'lifecycle workflow digest',
      'custom task extension digest',
      'Logic App run digest',
      'access package digest',
      'approval decision digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'Lifecycle Workflow history digest',
      'Logic App run receipt digest',
      'Graph operation receipt digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'workflow run digest',
      'task extension digest',
      'Graph operation digest',
    ]),
    riskSignals: Object.freeze([
      'privileged access package',
      'manager override',
      'leaver lifecycle change',
      'group owner change',
      'Logic App failure',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No Entra app, Logic App, Graph operation executor, identity store ownership, or access package ownership is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:sailpoint-workflows',
    targetSystem: 'sailpoint-workflows',
    targetFamily: 'iam-authority',
    displayName: 'SailPoint Workflows',
    primarySourceName: 'SailPoint Workflow Triggers',
    primarySourceUrl: 'https://documentation.sailpoint.com/saas/help/workflows/workflow-triggers.html',
    pattern: 'identity-workflow-gate',
    readiness: 'recipe-ready',
    insertionPoint: 'Before a SailPoint workflow routes or executes access-request, account, entitlement, identity lifecycle, CIEM scope, or external-trigger consequences.',
    attestorPlacement: 'Attestor receives digest-only identity, account, entitlement, source, access request, trigger, and approval refs before the customer-owned SailPoint workflow proceeds.',
    protectedConsequences: Object.freeze([
      'access.request.route',
      'account.update',
      'entitlement.change',
      'identity.lifecycle.process',
      'ciem.scope.change',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'access request digest',
      'identity digest',
      'source account digest',
      'entitlement digest',
      'approval decision digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'SailPoint workflow execution digest',
      'access decision digest',
      'source account event digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'workflow trigger digest',
      'access request digest',
      'source account operation digest',
    ]),
    riskSignals: Object.freeze([
      'privileged entitlement',
      'CIEM scope deselected',
      'external trigger',
      'account delete',
      'multi-approval decision',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No SailPoint connector, access governance ownership, provisioning engine, or identity source ownership is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:hl7-fhir-subscriptions',
    targetSystem: 'hl7-fhir-subscriptions',
    targetFamily: 'health-clinical',
    displayName: 'HL7 FHIR Subscriptions',
    primarySourceName: 'HL7 FHIR Subscriptions',
    primarySourceUrl: 'https://hl7.org/fhir/subscriptions.html',
    pattern: 'clinical-event-gate',
    readiness: 'requires-target-design',
    insertionPoint: 'Before a FHIR Subscription notification, clinical event dispatch, care-gap notification, or sensitive-data release reaches a downstream subscriber.',
    attestorPlacement: 'Attestor receives digest-only patient/subject, subscription topic, data class, consent, event, and approval refs before the customer-owned FHIR subscriber dispatch proceeds.',
    protectedConsequences: Object.freeze([
      'patient.event.notify',
      'care_gap.notify',
      'clinical.data.release',
      'consent.sensitive_event',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'FHIR resource digest',
      'SubscriptionTopic digest',
      'consent or authorization digest',
      'data classification digest',
      'recipient/subscriber digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'FHIR notification digest',
      'subscriber delivery digest',
      'audit event digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'subscription id digest',
      'event id digest',
      'notification delivery digest',
    ]),
    riskSignals: Object.freeze([
      'sensitive data class',
      'unexpected subscriber',
      'consent missing',
      'large cohort',
      'clinical urgency mismatch',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No EHR integration, FHIR server, clinical record ownership, care-management workflow, HIPAA compliance proof, or clinical decision authority is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:cds-hooks-clinical-decision-support',
    targetSystem: 'cds-hooks-clinical-decision-support',
    targetFamily: 'health-clinical',
    displayName: 'CDS Hooks clinical decision support',
    primarySourceName: 'CDS Hooks specification',
    primarySourceUrl: 'https://cds-hooks.org/specification/current/',
    pattern: 'clinical-event-gate',
    readiness: 'requires-target-design',
    insertionPoint: 'Before a CDS Hooks service response, card, suggestion, or clinical recommendation is shown or routed as actionable decision support.',
    attestorPlacement: 'Attestor receives digest-only hook, context, patient/subject, card, suggestion, evidence, and approval refs before the customer-owned CDS Client presents or routes it.',
    protectedConsequences: Object.freeze([
      'cds.card.present',
      'order.suggest',
      'prior_auth.prompt',
      'care_recommendation.notify',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'hook context digest',
      'card digest',
      'suggestion digest',
      'clinical evidence digest',
      'patient consent or policy digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'CDS response digest',
      'card presentation digest',
      'clinician action receipt digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'hook request digest',
      'card digest',
      'suggestion digest',
    ]),
    riskSignals: Object.freeze([
      'interruptive alert',
      'therapy recommendation',
      'prior authorization prompt',
      'missing clinical evidence',
      'stale context',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No CDS service, EHR integration, clinical validation, medical device claim, HIPAA compliance proof, or clinical decision authority is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:guidewire-claimcenter-cloud-api',
    targetSystem: 'guidewire-claimcenter-cloud-api',
    targetFamily: 'insurance-core',
    displayName: 'Guidewire ClaimCenter Cloud API',
    primarySourceName: 'Guidewire ClaimCenter Cloud API',
    primarySourceUrl: 'https://docs.guidewire.com/cloud/cc/202603/apiref/',
    pattern: 'insurance-api-gate',
    readiness: 'requires-target-design',
    insertionPoint: 'Before a customer-owned ClaimCenter API caller creates or changes claims, reserves, assignments, payments, notes, or claim lifecycle state.',
    attestorPlacement: 'Attestor receives digest-only claim, policy, party, reserve, payment, adjuster, evidence, and approval refs before the customer-owned ClaimCenter API caller proceeds.',
    protectedConsequences: Object.freeze([
      'claim.adjust',
      'reserve.change',
      'payment.prepare',
      'claim.assignment.update',
      'fnol.create',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'claim digest',
      'policy digest',
      'coverage digest',
      'loss evidence digest',
      'adjuster approval digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'ClaimCenter API response digest',
      'claim history event digest',
      'payment or reserve receipt digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'claim id digest',
      'operation id digest',
      'claim history digest',
    ]),
    riskSignals: Object.freeze([
      'reserve increase',
      'payment prepare',
      'coverage conflict',
      'new payee',
      'missing loss evidence',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No Guidewire app, ClaimCenter integration, claim record ownership, payment execution, regulatory filing, or insurance compliance proof is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
  createRecipe({
    recipeId: 'domain:guidewire-policycenter-cloud-api',
    targetSystem: 'guidewire-policycenter-cloud-api',
    targetFamily: 'insurance-core',
    displayName: 'Guidewire PolicyCenter Cloud API',
    primarySourceName: 'Guidewire PolicyCenter Cloud API',
    primarySourceUrl: 'https://docs.guidewire.com/cloud/pc/202603/apiref/',
    pattern: 'insurance-api-gate',
    readiness: 'requires-target-design',
    insertionPoint: 'Before a customer-owned PolicyCenter API caller changes quote, submission, policy, endorsement, account, or underwriting state.',
    attestorPlacement: 'Attestor receives digest-only policy, account, quote, underwriting, coverage, premium, evidence, and approval refs before the customer-owned PolicyCenter API caller proceeds.',
    protectedConsequences: Object.freeze([
      'policy.issue.prepare',
      'endorsement.change',
      'quote.update',
      'underwriting.referral.route',
      'coverage.change',
    ]),
    normalizedFields: BASE_NORMALIZED_FIELDS,
    evidenceRefs: Object.freeze([
      'policy digest',
      'quote digest',
      'coverage digest',
      'underwriting evidence digest',
      'approval decision digest',
    ]),
    approvalPath: BASE_APPROVAL_PATH,
    receiptRefs: Object.freeze([
      'PolicyCenter API response digest',
      'policy transaction digest',
      'underwriting decision receipt digest',
    ]),
    replayAndIdempotencyRefs: Object.freeze([
      'policy id digest',
      'quote id digest',
      'policy transaction digest',
    ]),
    riskSignals: Object.freeze([
      'coverage expansion',
      'premium change',
      'underwriting override',
      'policy issue prepare',
      'account mismatch',
    ]),
    implementationSteps: BASE_IMPLEMENTATION_STEPS,
    noGoBoundary: 'No Guidewire app, PolicyCenter integration, policy record ownership, rating engine, underwriting decision authority, or insurance compliance proof is implemented.',
    customerOwnsSystemOfRecord: true,
    nativeConnectorImplemented: false,
    customerDeploymentRequired: true,
    approvalRequired: true,
    autoEnforce: false,
    rawPayloadStored: false,
    recordsSystem: false,
    workflowWorkspace: false,
    productionReady: false,
  }),
] satisfies readonly DomainConsequenceRecipe[]);
